/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.core.BlockPos
 *  net.minecraft.core.Direction$Axis
 *  net.minecraft.core.Holder
 *  net.minecraft.util.RandomSource
 *  net.minecraft.world.entity.EntityType
 *  net.minecraft.world.item.DyeColor
 *  net.minecraft.world.level.BlockGetter
 *  net.minecraft.world.level.block.Block
 *  net.minecraft.world.level.block.DoorBlock
 *  net.minecraft.world.level.block.FenceBlock
 *  net.minecraft.world.level.block.FenceGateBlock
 *  net.minecraft.world.level.block.LeavesBlock
 *  net.minecraft.world.level.block.PressurePlateBlock
 *  net.minecraft.world.level.block.PressurePlateBlock$Sensitivity
 *  net.minecraft.world.level.block.RotatedPillarBlock
 *  net.minecraft.world.level.block.SaplingBlock
 *  net.minecraft.world.level.block.SlabBlock
 *  net.minecraft.world.level.block.SoundType
 *  net.minecraft.world.level.block.StairBlock
 *  net.minecraft.world.level.block.TrapDoorBlock
 *  net.minecraft.world.level.block.WoodButtonBlock
 *  net.minecraft.world.level.block.grower.AbstractTreeGrower
 *  net.minecraft.world.level.block.state.BlockBehaviour$Properties
 *  net.minecraft.world.level.block.state.BlockBehaviour$StateArgumentPredicate
 *  net.minecraft.world.level.block.state.BlockBehaviour$StatePredicate
 *  net.minecraft.world.level.block.state.BlockState
 *  net.minecraft.world.level.block.state.properties.Property
 *  net.minecraft.world.level.levelgen.feature.ConfiguredFeature
 *  net.minecraft.world.level.levelgen.feature.configurations.TreeConfiguration
 *  net.minecraft.world.level.material.MapColor
 *  net.minecraft.world.level.material.MapColor
 */
package ic2.core.ref;

import ic2.core.IC2;
import ic2.core.block.generator.tileentity.TileEntityCreativeGenerator;
import ic2.core.block.generator.tileentity.TileEntityGenerator;
import ic2.core.block.generator.tileentity.TileEntityGeoGenerator;
import ic2.core.block.generator.tileentity.TileEntityKineticGenerator;
import ic2.core.block.generator.tileentity.TileEntityRTGenerator;
import ic2.core.block.generator.tileentity.TileEntitySemifluidGenerator;
import ic2.core.block.generator.tileentity.TileEntitySolarGenerator;
import ic2.core.block.generator.tileentity.TileEntityStirlingGenerator;
import ic2.core.block.generator.tileentity.TileEntityWaterGenerator;
import ic2.core.block.generator.tileentity.TileEntityWindGenerator;
import ic2.core.block.heatgenerator.tileentity.TileEntityElectricHeatGenerator;
import ic2.core.block.heatgenerator.tileentity.TileEntityFluidHeatGenerator;
import ic2.core.block.heatgenerator.tileentity.TileEntityRTHeatGenerator;
import ic2.core.block.heatgenerator.tileentity.TileEntitySolidHeatGenerator;
import ic2.core.block.inherit.Ic2FenceBlock;
import ic2.core.block.inherit.Ic2GlassBlock;
import ic2.core.block.inherit.Ic2SheetBlock;
import ic2.core.block.inherit.Ic2SignBlock;
import ic2.core.block.inherit.Ic2WallSignBlock;
import ic2.core.block.kineticgenerator.tileentity.TileEntityElectricKineticGenerator;
import ic2.core.block.kineticgenerator.tileentity.TileEntityManualKineticGenerator;
import ic2.core.block.kineticgenerator.tileentity.TileEntitySteamKineticGenerator;
import ic2.core.block.kineticgenerator.tileentity.TileEntityStirlingKineticGenerator;
import ic2.core.block.kineticgenerator.tileentity.TileEntityWaterKineticGenerator;
import ic2.core.block.kineticgenerator.tileentity.TileEntityWindKineticGenerator;
import ic2.core.block.machine.MiningPipeBlock;
import ic2.core.block.machine.tileentity.TileEntityAdvMiner;
import ic2.core.block.machine.tileentity.TileEntityAssemblyBench;
import ic2.core.block.machine.tileentity.TileEntityBatchCrafter;
import ic2.core.block.machine.tileentity.TileEntityBlastFurnace;
import ic2.core.block.machine.tileentity.TileEntityBlockCutter;
import ic2.core.block.machine.tileentity.TileEntityBridgeNuke;
import ic2.core.block.machine.tileentity.TileEntityCanner;
import ic2.core.block.machine.tileentity.TileEntityCentrifuge;
import ic2.core.block.machine.tileentity.TileEntityChunkloader;
import ic2.core.block.machine.tileentity.TileEntityClassicCanner;
import ic2.core.block.machine.tileentity.TileEntityClassicCropmatron;
import ic2.core.block.machine.tileentity.TileEntityClassicElectrolyzer;
import ic2.core.block.machine.tileentity.TileEntityClassicMassFabricator;
import ic2.core.block.machine.tileentity.TileEntityCompressor;
import ic2.core.block.machine.tileentity.TileEntityCondenser;
import ic2.core.block.machine.tileentity.TileEntityCropHarvester;
import ic2.core.block.machine.tileentity.TileEntityCropmatron;
import ic2.core.block.machine.tileentity.TileEntityElectricFurnace;
import ic2.core.block.machine.tileentity.TileEntityElectrolyzer;
import ic2.core.block.machine.tileentity.TileEntityExtractor;
import ic2.core.block.machine.tileentity.TileEntityFermenter;
import ic2.core.block.machine.tileentity.TileEntityFluidBottler;
import ic2.core.block.machine.tileentity.TileEntityFluidDistributor;
import ic2.core.block.machine.tileentity.TileEntityFluidRegulator;
import ic2.core.block.machine.tileentity.TileEntityITnt;
import ic2.core.block.machine.tileentity.TileEntityInduction;
import ic2.core.block.machine.tileentity.TileEntityIndustrialWorkbench;
import ic2.core.block.machine.tileentity.TileEntityIronFurnace;
import ic2.core.block.machine.tileentity.TileEntityItemBuffer;
import ic2.core.block.machine.tileentity.TileEntityLiquidHeatExchanger;
import ic2.core.block.machine.tileentity.TileEntityMacerator;
import ic2.core.block.machine.tileentity.TileEntityMagnetizer;
import ic2.core.block.machine.tileentity.TileEntityMassFabricator;
import ic2.core.block.machine.tileentity.TileEntityMatter;
import ic2.core.block.machine.tileentity.TileEntityMetalFormer;
import ic2.core.block.machine.tileentity.TileEntityMiner;
import ic2.core.block.machine.tileentity.TileEntityNuke;
import ic2.core.block.machine.tileentity.TileEntityOreWashing;
import ic2.core.block.machine.tileentity.TileEntityPatternStorage;
import ic2.core.block.machine.tileentity.TileEntityPump;
import ic2.core.block.machine.tileentity.TileEntityRecycler;
import ic2.core.block.machine.tileentity.TileEntityReplicator;
import ic2.core.block.machine.tileentity.TileEntityScanner;
import ic2.core.block.machine.tileentity.TileEntitySolarDestiller;
import ic2.core.block.machine.tileentity.TileEntitySolidCanner;
import ic2.core.block.machine.tileentity.TileEntitySortingMachine;
import ic2.core.block.machine.tileentity.TileEntitySteamGenerator;
import ic2.core.block.machine.tileentity.TileEntitySteamRepressurizer;
import ic2.core.block.machine.tileentity.TileEntityTank;
import ic2.core.block.machine.tileentity.TileEntityTeleporter;
import ic2.core.block.machine.tileentity.TileEntityTerra;
import ic2.core.block.machine.tileentity.TileEntityTesla;
import ic2.core.block.machine.tileentity.TileEntityWeightedFluidDistributor;
import ic2.core.block.machine.tileentity.TileEntityWeightedItemDistributor;
import ic2.core.block.misc.FoamBlock;
import ic2.core.block.misc.RubberLogBlock;
import ic2.core.block.misc.RubberWoodBlock;
import ic2.core.block.misc.ScaffoldBlock;
import ic2.core.block.misc.WallBlock;
import ic2.core.block.personal.TileEntityEnergyOMat;
import ic2.core.block.personal.TileEntityPersonalChest;
import ic2.core.block.personal.TileEntityTradeOMat;
import ic2.core.block.reactor.tileentity.TileEntityNuclearReactorElectric;
import ic2.core.block.reactor.tileentity.TileEntityRCI_LZH;
import ic2.core.block.reactor.tileentity.TileEntityRCI_RSH;
import ic2.core.block.reactor.tileentity.TileEntityReactorAccessHatch;
import ic2.core.block.reactor.tileentity.TileEntityReactorChamberElectric;
import ic2.core.block.reactor.tileentity.TileEntityReactorFluidPort;
import ic2.core.block.reactor.tileentity.TileEntityReactorRedstonePort;
import ic2.core.block.storage.box.TileEntityBronzeStorageBox;
import ic2.core.block.storage.box.TileEntityIridiumStorageBox;
import ic2.core.block.storage.box.TileEntityIronStorageBox;
import ic2.core.block.storage.box.TileEntitySteelStorageBox;
import ic2.core.block.storage.box.TileEntityWoodenStorageBox;
import ic2.core.block.storage.tank.TileEntityBronzeTank;
import ic2.core.block.storage.tank.TileEntityIridiumTank;
import ic2.core.block.storage.tank.TileEntityIronTank;
import ic2.core.block.storage.tank.TileEntitySteelTank;
import ic2.core.block.tileentity.Ic2TileEntityBlock;
import ic2.core.block.tileentity.TileEntityWall;
import ic2.core.block.wiring.CableBlock;
import ic2.core.block.wiring.CableType;
import ic2.core.block.wiring.DetectorCableBlock;
import ic2.core.block.wiring.DetectorFoamCableBlock;
import ic2.core.block.wiring.FoamCableBlock;
import ic2.core.block.wiring.SplitterCableBlock;
import ic2.core.block.wiring.SplitterFoamCableBlock;
import ic2.core.block.wiring.tileentity.TileEntityChargepadBatBox;
import ic2.core.block.wiring.tileentity.TileEntityChargepadCESU;
import ic2.core.block.wiring.tileentity.TileEntityChargepadMFE;
import ic2.core.block.wiring.tileentity.TileEntityChargepadMFSU;
import ic2.core.block.wiring.tileentity.TileEntityElectricBatBox;
import ic2.core.block.wiring.tileentity.TileEntityElectricCESU;
import ic2.core.block.wiring.tileentity.TileEntityElectricMFE;
import ic2.core.block.wiring.tileentity.TileEntityElectricMFSU;
import ic2.core.block.wiring.tileentity.TileEntityTransformerEV;
import ic2.core.block.wiring.tileentity.TileEntityTransformerHV;
import ic2.core.block.wiring.tileentity.TileEntityTransformerLV;
import ic2.core.block.wiring.tileentity.TileEntityTransformerMV;
import ic2.core.crop.Ic2CropType;
import ic2.core.crop.TileEntityCrop;
import ic2.core.ref.IC2Material;
import ic2.core.ref.Ic2SignType;
import ic2.core.util.Util;
import ic2.core.world.Ic2WorldGen;
import java.util.Optional;
import java.util.function.Function;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.resources.ResourceKey;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.Registries;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.FenceBlock;
import net.minecraft.world.level.block.FenceGateBlock;
import net.minecraft.world.level.block.LeavesBlock;
import net.minecraft.world.level.block.PressurePlateBlock;
import net.minecraft.world.level.block.RotatedPillarBlock;
import net.minecraft.world.level.block.SaplingBlock;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.TrapDoorBlock;
import net.minecraft.world.level.block.ButtonBlock;
import net.minecraft.world.level.block.grower.TreeGrower;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.Property;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;
import net.minecraft.world.level.levelgen.feature.configurations.TreeConfiguration;
import net.minecraft.world.level.material.MapColor;
import net.minecraft.world.level.material.MapColor;

public final class Ic2Blocks {
    public static final Block BASALT = Ic2Blocks.register("basalt", new Block(BlockBehaviour.Properties.of().strength(20.0f, 45.0f).requiresCorrectToolForDrops()));
    public static final Block LEAD_ORE = Ic2Blocks.register("lead_ore", new Block(BlockBehaviour.Properties.of().strength(2.0f, 4.0f).requiresCorrectToolForDrops()));
    public static final Block TIN_ORE = Ic2Blocks.register("tin_ore", new Block(BlockBehaviour.Properties.of().strength(3.0f, 5.0f).requiresCorrectToolForDrops()));
    public static final Block URANIUM_ORE = Ic2Blocks.register("uranium_ore", new Block(BlockBehaviour.Properties.of().strength(4.0f, 6.0f).requiresCorrectToolForDrops()));
    public static final Block DEEPSLATE_LEAD_ORE = Ic2Blocks.register("deepslate_lead_ore", new Block(BlockBehaviour.Properties.of().mapColor(MapColor.DEEPSLATE).strength(3.0f, 6.0f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final Block DEEPSLATE_TIN_ORE = Ic2Blocks.register("deepslate_tin_ore", new Block(BlockBehaviour.Properties.of().mapColor(MapColor.DEEPSLATE).strength(4.0f, 7.0f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final Block DEEPSLATE_URANIUM_ORE = Ic2Blocks.register("deepslate_uranium_ore", new Block(BlockBehaviour.Properties.of().mapColor(MapColor.DEEPSLATE).strength(5.0f, 8.0f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final Block RAW_LEAD_BLOCK = Ic2Blocks.register("raw_lead_block", new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_LIGHT_GRAY).strength(3.0f, 11.0f).requiresCorrectToolForDrops()));
    public static final Block RAW_TIN_BLOCK = Ic2Blocks.register("raw_tin_block", new Block(BlockBehaviour.Properties.of().mapColor(MapColor.SNOW).strength(4.0f, 12.0f).requiresCorrectToolForDrops()));
    public static final Block RAW_URANIUM_BLOCK = Ic2Blocks.register("raw_uranium_block", new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GREEN).strength(5.0f, 13.0f).requiresCorrectToolForDrops()));
    public static final Block BRONZE_BLOCK = Ic2Blocks.register("bronze_block", new Block(BlockBehaviour.Properties.of().strength(5.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL)));
    public static final Block LEAD_BLOCK = Ic2Blocks.register("lead_block", new Block(BlockBehaviour.Properties.of().strength(4.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL)));
    public static final Block STEEL_BLOCK = Ic2Blocks.register("steel_block", new Block(BlockBehaviour.Properties.of().strength(8.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL)));
    public static final Block TIN_BLOCK = Ic2Blocks.register("tin_block", new Block(BlockBehaviour.Properties.of().strength(4.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL)));
    public static final Block URANIUM_BLOCK = Ic2Blocks.register("uranium_block", new Block(BlockBehaviour.Properties.of().strength(6.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL)));
    public static final Block REINFORCED_STONE = Ic2Blocks.register("reinforced_stone", new Block(BlockBehaviour.Properties.of().strength(80.0f, 180.0f).requiresCorrectToolForDrops()));
    public static final Block MACHINE = Ic2Blocks.register("machine", new Block(BlockBehaviour.Properties.of().strength(5.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL)));
    public static final Block ADVANCED_MACHINE = Ic2Blocks.register("advanced_machine", new Block(BlockBehaviour.Properties.of().strength(8.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL)));
    public static final Block REACTOR_VESSEL = Ic2Blocks.register("reactor_vessel", new Block(BlockBehaviour.Properties.of().strength(40.0f, 90.0f).requiresCorrectToolForDrops()));
    public static final Block SILVER_BLOCK = Ic2Blocks.register("silver_block", new Block(BlockBehaviour.Properties.of().strength(4.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL)));
    public static final LeavesBlock RUBBER_LEAVES = Ic2Blocks.register("rubber_leaves", new LeavesBlock(BlockBehaviour.Properties.of().strength(0.2f).randomTicks().sound(SoundType.GRASS).noOcclusion()));
    public static final RubberLogBlock RUBBER_LOG = Ic2Blocks.register("rubber_log", new RubberLogBlock(BlockBehaviour.Properties.of().mapColor(Ic2Blocks::lambda$static$0).strength(1.0f).sound(SoundType.WOOD)));
    public static final RotatedPillarBlock STRIPPED_RUBBER_LOG = Ic2Blocks.register("stripped_rubber_log", new RotatedPillarBlock(BlockBehaviour.Properties.of().mapColor(Ic2Blocks::lambda$static$0).strength(1.0f).sound(SoundType.WOOD)));
    public static final RubberWoodBlock RUBBER_WOOD = Ic2Blocks.register("rubber_wood", new RubberWoodBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BROWN).strength(1.0f).sound(SoundType.WOOD)));
    public static final Block STRIPPED_RUBBER_WOOD = Ic2Blocks.register("stripped_rubber_wood", new Block(BlockBehaviour.Properties.of().mapColor(MapColor.PODZOL).strength(1.0f).sound(SoundType.WOOD)));
    public static final Block RUBBER_SAPLING = Ic2Blocks.register("rubber_sapling", new SaplingBlock(new TreeGrower("rubber_tree", Optional.empty(), Optional.empty(), Optional.of(ResourceKey.create(Registries.CONFIGURED_FEATURE, IC2.getIdentifier("rubber_tree")))), BlockBehaviour.Properties.of().noCollission().randomTicks().instabreak().sound(SoundType.GRASS)));
    public static final Block RUBBER_PLANKS;
    public static final Block RUBBER_BUTTON;
    public static final Block RUBBER_DOOR;
    public static final Block RUBBER_FENCE;
    public static final Block RUBBER_FENCE_GATE;
    public static final Block RUBBER_PRESSURE_PLATE;
    public static final Block RUBBER_SIGN;
    public static final Block RUBBER_SLAB;
    public static final Block RUBBER_STAIRS;
    public static final Block RUBBER_TRAPDOOR;
    public static final Block RUBBER_WALL_SIGN;
    public static final Block WOODEN_SCAFFOLD;
    public static final Block REINFORCED_WOODEN_SCAFFOLD;
    public static final Block IRON_SCAFFOLD;
    public static final Block REINFORCED_IRON_SCAFFOLD;
    public static final Block IRON_FENCE;
    public static final Block RESIN_SHEET;
    public static final Block RUBBER_SHEET;
    public static final Block WOOL_SHEET;
    public static final Block REINFORCED_GLASS;
    public static final Block FOAM;
    private static final BlockBehaviour.Properties wallSettings;
    public static final Block WHITE_WALL;
    public static final Block ORANGE_WALL;
    public static final Block MAGENTA_WALL;
    public static final Block LIGHT_BLUE_WALL;
    public static final Block YELLOW_WALL;
    public static final Block LIME_WALL;
    public static final Block PINK_WALL;
    public static final Block GRAY_WALL;
    public static final Block LIGHT_GRAY_WALL;
    public static final Block CYAN_WALL;
    public static final Block PURPLE_WALL;
    public static final Block BLUE_WALL;
    public static final Block BROWN_WALL;
    public static final Block GREEN_WALL;
    public static final Block RED_WALL;
    public static final Block BLACK_WALL;
    public static final Block OBSCURED_WALL;
    public static final Block MINING_PIPE;
    public static final Block MINING_PIPE_TIP;
    public static final Block REINFORCED_DOOR;
    public static final Block ITNT;
    public static final Block NUKE;
    public static final Block CLASSIC_NUKE;
    public static final Block GENERATOR;
    public static final Block GEO_GENERATOR;
    public static final Block KINETIC_GENERATOR;
    public static final Block RT_GENERATOR;
    public static final Block SEMIFLUID_GENERATOR;
    public static final Block SOLAR_GENERATOR;
    public static final Block STIRLING_GENERATOR;
    public static final Block WATER_GENERATOR;
    public static final Block WIND_GENERATOR;
    public static final Block ELECTRIC_HEAT_GENERATOR;
    public static final Block FLUID_HEAT_GENERATOR;
    public static final Block RT_HEAT_GENERATOR;
    public static final Block SOLID_HEAT_GENERATOR;
    public static final Block ELECTRIC_KINETIC_GENERATOR;
    public static final Block MANUAL_KINETIC_GENERATOR;
    public static final Block STEAM_KINETIC_GENERATOR;
    public static final Block STIRLING_KINETIC_GENERATOR;
    public static final Block WATER_KINETIC_GENERATOR;
    public static final Block WIND_KINETIC_GENERATOR;
    public static final Block NUCLEAR_REACTOR;
    public static final Block REACTOR_ACCESS_HATCH;
    public static final Block REACTOR_CHAMBER;
    public static final Block REACTOR_FLUID_PORT;
    public static final Block REACTOR_REDSTONE_PORT;
    public static final Block CONDENSER;
    public static final Block FLUID_BOTTLER;
    public static final Block FLUID_DISTRIBUTOR;
    public static final Block FLUID_REGULATOR;
    public static final Block LIQUID_HEAT_EXCHANGER;
    public static final Block PUMP;
    public static final Block SOLAR_DISTILLER;
    public static final Block STEAM_GENERATOR;
    public static final Block ITEM_BUFFER;
    public static final Block MAGNETIZER;
    public static final Block SORTING_MACHINE;
    public static final Block TELEPORTER;
    public static final Block TERRAFORMER;
    public static final Block TESLA_COIL;
    public static final Block CANNER;
    public static final Block CLASSIC_CANNER;
    public static final Ic2TileEntityBlock COMPRESSOR;
    public static final Block ELECTRIC_FURNACE;
    public static final Ic2TileEntityBlock EXTRACTOR;
    public static final Block IRON_FURNACE;
    public static final Ic2TileEntityBlock MACERATOR;
    public static final Block RECYCLER;
    public static final Block SOLID_CANNER;
    public static final Ic2TileEntityBlock BLAST_FURNACE;
    public static final Ic2TileEntityBlock BLOCK_CUTTER;
    public static final Ic2TileEntityBlock CENTRIFUGE;
    public static final Block FERMENTER;
    public static final Block INDUCTION_FURNACE;
    public static final Ic2TileEntityBlock METAL_FORMER;
    public static final Ic2TileEntityBlock ORE_WASHING_PLANT;
    public static final Block ADVANCED_MINER;
    public static final Block CROP_HARVESTER;
    public static final Block CROPMATRON;
    public static final Block CLASSIC_CROPMATRON;
    public static final Block MINER;
    public static final Block MASS_FABRICATOR;
    public static final Block CLASSIC_MASS_FABRICATOR;
    public static final Block UU_ASSEMBLY_BENCH;
    public static final Block MATTER_GENERATOR;
    public static final Block PATTERN_STORAGE;
    public static final Block REPLICATOR;
    public static final Block UU_SCANNER;
    public static final Block ENERGY_O_MAT;
    public static final Block PERSONAL_CHEST;
    public static final Block TRADE_O_MAT;
    private static final BlockBehaviour.Properties cableSettings;
    private static final BlockBehaviour.Properties insulatedCableSettings;
    public static final FoamCableBlock COPPER_FOAM_CABLE;
    public static final Block COPPER_CABLE;
    public static final FoamCableBlock INSULATED_COPPER_FOAM_CABLE;
    public static final Block INSULATED_COPPER_CABLE;
    public static final FoamCableBlock GLASS_FIBRE_FOAM_CABLE;
    public static final Block GLASS_FIBRE_CABLE;
    public static final FoamCableBlock GOLD_FOAM_CABLE;
    public static final Block GOLD_CABLE;
    public static final FoamCableBlock INSULATED_GOLD_FOAM_CABLE;
    public static final Block INSULATED_GOLD_CABLE;
    public static final FoamCableBlock DOUBLE_INSULATED_GOLD_FOAM_CABLE;
    public static final Block DOUBLE_INSULATED_GOLD_CABLE;
    public static final FoamCableBlock IRON_FOAM_CABLE;
    public static final Block IRON_CABLE;
    public static final FoamCableBlock INSULATED_IRON_FOAM_CABLE;
    public static final Block INSULATED_IRON_CABLE;
    public static final FoamCableBlock DOUBLE_INSULATED_IRON_FOAM_CABLE;
    public static final Block DOUBLE_INSULATED_IRON_CABLE;
    public static final FoamCableBlock TRIPLE_INSULATED_IRON_FOAM_CABLE;
    public static final Block TRIPLE_INSULATED_IRON_CABLE;
    public static final FoamCableBlock TIN_FOAM_CABLE;
    public static final Block TIN_CABLE;
    public static final FoamCableBlock INSULATED_TIN_FOAM_CABLE;
    public static final Block INSULATED_TIN_CABLE;
    public static final DetectorFoamCableBlock DETECTOR_FOAM_CABLE;
    public static final Block DETECTOR_CABLE;
    public static final SplitterFoamCableBlock SPLITTER_FOAM_CABLE;
    public static final Block SPLITTER_CABLE;
    public static final Block BATBOX_CHARGEPAD;
    public static final Block CESU_CHARGEPAD;
    public static final Block MFE_CHARGEPAD;
    public static final Block MFSU_CHARGEPAD;
    public static final Block BATBOX;
    public static final Block CESU;
    public static final Block MFE;
    public static final Block CLASSIC_MFE;
    public static final Block MFSU;
    public static final Block CLASSIC_MFSU;
    public static final Block ELECTROLYZER;
    public static final Block CLASSIC_ELECTROLYZER;
    public static final Block LV_TRANSFORMER;
    public static final Block MV_TRANSFORMER;
    public static final Block HV_TRANSFORMER;
    public static final Block EV_TRANSFORMER;
    public static final Block TANK;
    public static final Block CHUNK_LOADER;
    public static final Block CREATIVE_GENERATOR;
    public static final Block STEAM_REPRESSURIZER;
    public static final Block WEIGHTED_FLUID_DISTRIBUTOR;
    public static final Block WEIGHTED_ITEM_DISTRIBUTOR;
    public static final Block RCI_RSH;
    public static final Block RCI_LZH;
    private static final BlockBehaviour.Properties cropSettings;
    public static final Block CROP_STICK;
    public static final Block WEED_CROP;
    public static final Block WHEAT_CROP;
    public static final Block CARROTS_CROP;
    public static final Block POTATO_CROP;
    public static final Block BEETROOTS_CROP;
    public static final Block PUMPKIN_CROP;
    public static final Block MELON_CROP;
    public static final Block DANDELION_CROP;
    public static final Block POPPY_CROP;
    public static final Block BLACKTHORN_CROP;
    public static final Block TULIP_CROP;
    public static final Block CYAZINT_CROP;
    public static final Block VENOMILIA_CROP;
    public static final Block REED_CROP;
    public static final Block STICKY_REED_CROP;
    public static final Block COCOA_CROP;
    public static final Block FLAX_CROP;
    public static final Block RED_MUSHROOM_CROP;
    public static final Block BROWN_MUSHROOM_CROP;
    public static final Block NETHER_WART_CROP;
    public static final Block TERRA_WART_CROP;
    public static final Block OAK_SAPLING_CROP;
    public static final Block SPRUCE_SAPLING_CROP;
    public static final Block BIRCH_SAPLING_CROP;
    public static final Block JUNGLE_SAPLING_CROP;
    public static final Block ACACIA_SAPLING_CROP;
    public static final Block DARK_OAK_SAPLING_CROP;
    public static final Block FERRU_CROP;
    public static final Block CYPRIUM_CROP;
    public static final Block STAGNIUM_CROP;
    public static final Block PLUMBISCUS_CROP;
    public static final Block AURELIA_CROP;
    public static final Block SHINING_CROP;
    public static final Block RED_WHEAT_CROP;
    public static final Block COFFEE_CROP;
    public static final Block HOPS_CROP;
    public static final Block EATING_PLANT_CROP;
    public static final Block INDUSTRIAL_WORKBENCH;
    public static final Block BATCH_CRAFTER;
    public static final Block WOODEN_STORAGE_BOX;
    public static final Block IRON_STORAGE_BOX;
    public static final Block BRONZE_STORAGE_BOX;
    public static final Block STEEL_STORAGE_BOX;
    public static final Block IRIDIUM_STORAGE_BOX;
    public static final Block BRONZE_TANK;
    public static final Block IRON_TANK;
    public static final Block STEEL_TANK;
    public static final Block IRIDIUM_TANK;

    public static void init() {
    }

    private static <T extends Block> T register(String string, T t) {
        IC2.envProxy.registerBlock(IC2.getIdentifier(string), t);
        return t;
    }

    private static boolean never(BlockState blockState, BlockGetter blockGetter, BlockPos blockPos) {
        return false;
    }

    private static Boolean never(BlockState blockState, BlockGetter blockGetter, BlockPos blockPos, EntityType<?> entityType) {
        return false;
    }

    private static Boolean canSpawnOnLeaves(BlockState blockState, BlockGetter blockGetter, BlockPos blockPos, EntityType<?> entityType) {
        return entityType == EntityType.OCELOT || entityType == EntityType.PARROT;
    }

    private static /* synthetic */ boolean lambda$static$2(BlockState blockState, BlockGetter blockGetter, BlockPos blockPos, EntityType entityType) {
        return false;
    }

    private static /* synthetic */ MapColor lambda$static$0(BlockState blockState) {
        return blockState.getValue((Property)RotatedPillarBlock.AXIS) == Direction.Axis.Y ? MapColor.PODZOL : MapColor.COLOR_BROWN;
    }

    static {
        IC2.envProxy.registerFlammableBlock((Block)RUBBER_LEAVES, 20, 30);
        IC2.envProxy.registerFlammableBlock((Block)RUBBER_LOG, 20, 4);
        RUBBER_PLANKS = Ic2Blocks.register("rubber_planks", new Block(BlockBehaviour.Properties.of().mapColor(MapColor.PODZOL).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
        RUBBER_BUTTON = Ic2Blocks.register("rubber_button", new ButtonBlock(BlockSetType.OAK, 30, BlockBehaviour.Properties.of().noCollission().strength(0.5f).sound(SoundType.WOOD)));
        RUBBER_DOOR = Ic2Blocks.register("rubber_door", new DoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.of().mapColor(RUBBER_PLANKS.defaultMapColor()).strength(3.0f).sound(SoundType.WOOD).noOcclusion()){});
        RUBBER_FENCE = Ic2Blocks.register("rubber_fence", new FenceBlock(BlockBehaviour.Properties.of().mapColor(RUBBER_PLANKS.defaultMapColor()).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
        RUBBER_FENCE_GATE = Ic2Blocks.register("rubber_fence_gate", new FenceGateBlock(WoodType.OAK, BlockBehaviour.Properties.of().mapColor(RUBBER_PLANKS.defaultMapColor()).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
        RUBBER_PRESSURE_PLATE = Ic2Blocks.register("rubber_pressure_plate", new PressurePlateBlock(BlockSetType.OAK, BlockBehaviour.Properties.of().mapColor(RUBBER_PLANKS.defaultMapColor()).noCollission().strength(0.5f).sound(SoundType.WOOD)){});
        RUBBER_SIGN = Ic2Blocks.register("rubber_sign", new Ic2SignBlock(BlockBehaviour.Properties.of().mapColor(RUBBER_LOG.defaultMapColor()).noCollission().strength(1.0f).sound(SoundType.WOOD), Ic2SignType.RUBBER));
        RUBBER_SLAB = Ic2Blocks.register("rubber_slab", new SlabBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
        RUBBER_STAIRS = Ic2Blocks.register("rubber_stairs", new StairBlock(RUBBER_PLANKS.defaultBlockState(), BlockBehaviour.Properties.of().mapColor(MapColor.PODZOL).strength(2.0f, 3.0f).sound(SoundType.WOOD)){});
        RUBBER_TRAPDOOR = Ic2Blocks.register("rubber_trapdoor", new TrapDoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.of().mapColor(MapColor.PODZOL).strength(3.0f).sound(SoundType.WOOD).noOcclusion().isValidSpawn((state, getter, pos, type) -> false)){});
        RUBBER_WALL_SIGN = Ic2Blocks.register("rubber_wall_sign", new Ic2WallSignBlock(BlockBehaviour.Properties.of().mapColor(RUBBER_LOG.defaultMapColor()).noCollission().strength(1.0f).sound(SoundType.WOOD).dropsLike(RUBBER_SIGN), Ic2SignType.RUBBER));
        WOODEN_SCAFFOLD = Ic2Blocks.register("wooden_scaffold", new ScaffoldBlock(BlockBehaviour.Properties.of().noOcclusion().strength(0.5f, 0.12f).randomTicks().sound(SoundType.WOOD), 2));
        REINFORCED_WOODEN_SCAFFOLD = Ic2Blocks.register("reinforced_wooden_scaffold", new ScaffoldBlock(BlockBehaviour.Properties.of().noOcclusion().strength(0.6f, 0.24f).randomTicks().sound(SoundType.WOOD), 5));
        IRON_SCAFFOLD = Ic2Blocks.register("iron_scaffold", new ScaffoldBlock(BlockBehaviour.Properties.of().noOcclusion().strength(0.8f, 6.0f).randomTicks().sound(SoundType.METAL), 5));
        REINFORCED_IRON_SCAFFOLD = Ic2Blocks.register("reinforced_iron_scaffold", new ScaffoldBlock(BlockBehaviour.Properties.of().noOcclusion().strength(1.0f, 8.0f).randomTicks().sound(SoundType.METAL), 12));
        IC2.envProxy.registerFlammableBlock(WOODEN_SCAFFOLD, 8, 20);
        IC2.envProxy.registerFlammableBlock(REINFORCED_WOODEN_SCAFFOLD, 8, 20);
        IRON_FENCE = Ic2Blocks.register("iron_fence", new Ic2FenceBlock(BlockBehaviour.Properties.of().strength(5.0f, 10.0f), true));
        RESIN_SHEET = Ic2Blocks.register("resin_sheet", new Ic2SheetBlock(BlockBehaviour.Properties.of().strength(1.6f, 0.5f)));
        RUBBER_SHEET = Ic2Blocks.register("rubber_sheet", new Ic2SheetBlock(BlockBehaviour.Properties.of().strength(0.8f, 2.0f)));
        WOOL_SHEET = Ic2Blocks.register("wool_sheet", new Ic2SheetBlock(BlockBehaviour.Properties.of().strength(0.8f, 0.8f)));
        REINFORCED_GLASS = Ic2Blocks.register("reinforced_glass", new Ic2GlassBlock(BlockBehaviour.Properties.of().noOcclusion().strength(5.0f, 180.0f).sound(SoundType.GLASS).isValidSpawn(Ic2Blocks::lambda$static$2)));
        FOAM = Ic2Blocks.register("foam", new FoamBlock(BlockBehaviour.Properties.of().noOcclusion().strength(0.01f, 10.0f).randomTicks().sound(SoundType.WOOL)));
        wallSettings = BlockBehaviour.Properties.of().strength(3.0f, 30.0f).requiresCorrectToolForDrops().sound(SoundType.STONE);
        WHITE_WALL = Ic2Blocks.register("white_wall", new WallBlock(wallSettings, DyeColor.WHITE));
        ORANGE_WALL = Ic2Blocks.register("orange_wall", new WallBlock(wallSettings, DyeColor.ORANGE));
        MAGENTA_WALL = Ic2Blocks.register("magenta_wall", new WallBlock(wallSettings, DyeColor.MAGENTA));
        LIGHT_BLUE_WALL = Ic2Blocks.register("light_blue_wall", new WallBlock(wallSettings, DyeColor.LIGHT_BLUE));
        YELLOW_WALL = Ic2Blocks.register("yellow_wall", new WallBlock(wallSettings, DyeColor.YELLOW));
        LIME_WALL = Ic2Blocks.register("lime_wall", new WallBlock(wallSettings, DyeColor.LIME));
        PINK_WALL = Ic2Blocks.register("pink_wall", new WallBlock(wallSettings, DyeColor.PINK));
        GRAY_WALL = Ic2Blocks.register("gray_wall", new WallBlock(wallSettings, DyeColor.GRAY));
        LIGHT_GRAY_WALL = Ic2Blocks.register("light_gray_wall", new WallBlock(wallSettings, DyeColor.LIGHT_GRAY));
        CYAN_WALL = Ic2Blocks.register("cyan_wall", new WallBlock(wallSettings, DyeColor.CYAN));
        PURPLE_WALL = Ic2Blocks.register("purple_wall", new WallBlock(wallSettings, DyeColor.PURPLE));
        BLUE_WALL = Ic2Blocks.register("blue_wall", new WallBlock(wallSettings, DyeColor.BLUE));
        BROWN_WALL = Ic2Blocks.register("brown_wall", new WallBlock(wallSettings, DyeColor.BROWN));
        GREEN_WALL = Ic2Blocks.register("green_wall", new WallBlock(wallSettings, DyeColor.GREEN));
        RED_WALL = Ic2Blocks.register("red_wall", new WallBlock(wallSettings, DyeColor.RED));
        BLACK_WALL = Ic2Blocks.register("black_wall", new WallBlock(wallSettings, DyeColor.BLACK));
        OBSCURED_WALL = Ic2Blocks.register("obscured_wall", Ic2TileEntityBlock.create(wallSettings, TileEntityWall.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false));
        MINING_PIPE = Ic2Blocks.register("mining_pipe", new MiningPipeBlock(BlockBehaviour.Properties.of().strength(6.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL)));
        MINING_PIPE_TIP = Ic2Blocks.register("mining_pipe_tip", new Block(BlockBehaviour.Properties.of().strength(6.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL)));
        REINFORCED_DOOR = Ic2Blocks.register("reinforced_door", new DoorBlock(BlockSetType.IRON, BlockBehaviour.Properties.of().strength(50.0f, 150.0f).sound(SoundType.METAL)){});
        ITNT = Ic2Blocks.register("itnt", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(0.0f, 0.0f).sound(SoundType.GRASS), TileEntityITnt.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false));
        NUKE = Ic2Blocks.register("nuke", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(0.0f, 0.0f).sound(SoundType.GRASS), TileEntityNuke.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false));
        CLASSIC_NUKE = Ic2Blocks.register("classic_nuke", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(0.0f, 0.0f).sound(SoundType.GRASS), TileEntityBridgeNuke.TileEntityClassicNuke.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false));
        GENERATOR = Ic2Blocks.register("generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
        GEO_GENERATOR = Ic2Blocks.register("geo_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityGeoGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Generator, Util.horizontalFacings, true));
        KINETIC_GENERATOR = Ic2Blocks.register("kinetic_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityKineticGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Generator, Util.allFacings, true));
        RT_GENERATOR = Ic2Blocks.register("rt_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityRTGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Generator, Util.noFacings, false));
        SEMIFLUID_GENERATOR = Ic2Blocks.register("semifluid_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySemifluidGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Generator, Util.horizontalFacings, true));
        SOLAR_GENERATOR = Ic2Blocks.register("solar_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySolarGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Generator, Util.horizontalFacings, true));
        STIRLING_GENERATOR = Ic2Blocks.register("stirling_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityStirlingGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Generator, Util.allFacings, true));
        WATER_GENERATOR = Ic2Blocks.register("water_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityWaterGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Generator, Util.horizontalFacings, true));
        WIND_GENERATOR = Ic2Blocks.register("wind_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityWindGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Generator, Util.horizontalFacings, true));
        ELECTRIC_HEAT_GENERATOR = Ic2Blocks.register("electric_heat_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityElectricHeatGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.allFacings, true));
        FLUID_HEAT_GENERATOR = Ic2Blocks.register("fluid_heat_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityFluidHeatGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.allFacings, true));
        RT_HEAT_GENERATOR = Ic2Blocks.register("rt_heat_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityRTHeatGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.allFacings, true));
        SOLID_HEAT_GENERATOR = Ic2Blocks.register("solid_heat_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySolidHeatGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.allFacings, true));
        ELECTRIC_KINETIC_GENERATOR = Ic2Blocks.register("electric_kinetic_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityElectricKineticGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.allFacings, true));
        MANUAL_KINETIC_GENERATOR = Ic2Blocks.register("manual_kinetic_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityManualKineticGenerator.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.allFacings, true));
        STEAM_KINETIC_GENERATOR = Ic2Blocks.register("steam_kinetic_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySteamKineticGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.allFacings, true));
        STIRLING_KINETIC_GENERATOR = Ic2Blocks.register("stirling_kinetic_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityStirlingKineticGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.allFacings, true));
        WATER_KINETIC_GENERATOR = Ic2Blocks.register("water_kinetic_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityWaterKineticGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
        WIND_KINETIC_GENERATOR = Ic2Blocks.register("wind_kinetic_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityWindKineticGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
        NUCLEAR_REACTOR = Ic2Blocks.register("nuclear_reactor", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityNuclearReactorElectric.class, true, Ic2TileEntityBlock.DefaultDrop.Generator, Util.horizontalFacings, true));
        REACTOR_ACCESS_HATCH = Ic2Blocks.register("reactor_access_hatch", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(40.0f, 90.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityReactorAccessHatch.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.onlyNorth, false));
        REACTOR_CHAMBER = Ic2Blocks.register("reactor_chamber", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityReactorChamberElectric.class, false, Ic2TileEntityBlock.DefaultDrop.Machine, Util.onlyNorth, true));
        REACTOR_FLUID_PORT = Ic2Blocks.register("reactor_fluid_port", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(40.0f, 90.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityReactorFluidPort.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.onlyNorth, false));
        REACTOR_REDSTONE_PORT = Ic2Blocks.register("reactor_redstone_port", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(40.0f, 90.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityReactorRedstonePort.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.onlyNorth, false));
        CONDENSER = Ic2Blocks.register("condenser", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityCondenser.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        FLUID_BOTTLER = Ic2Blocks.register("fluid_bottler", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityFluidBottler.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        FLUID_DISTRIBUTOR = Ic2Blocks.register("fluid_distributor", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityFluidDistributor.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
        FLUID_REGULATOR = Ic2Blocks.register("fluid_regulator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityFluidRegulator.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
        LIQUID_HEAT_EXCHANGER = Ic2Blocks.register("liquid_heat_exchanger", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityLiquidHeatExchanger.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
        PUMP = Ic2Blocks.register("pump", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityPump.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
        SOLAR_DISTILLER = Ic2Blocks.register("solar_distiller", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySolarDestiller.class, false, Ic2TileEntityBlock.DefaultDrop.Machine, Util.noFacings, false));
        STEAM_GENERATOR = Ic2Blocks.register("steam_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySteamGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
        ITEM_BUFFER = Ic2Blocks.register("item_buffer", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityItemBuffer.class, false, Ic2TileEntityBlock.DefaultDrop.Machine, Util.noFacings, false));
        MAGNETIZER = Ic2Blocks.register("magnetizer", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityMagnetizer.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
        SORTING_MACHINE = Ic2Blocks.register("sorting_machine", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySortingMachine.class, false, Ic2TileEntityBlock.DefaultDrop.Machine, Util.onlyNorth, false));
        TELEPORTER = Ic2Blocks.register("teleporter", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTeleporter.class, true, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.noFacings, false));
        TERRAFORMER = Ic2Blocks.register("terraformer", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTerra.class, true, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.noFacings, false));
        TESLA_COIL = Ic2Blocks.register("tesla_coil", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTesla.class, false, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        CANNER = Ic2Blocks.register("canner", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityCanner.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        CLASSIC_CANNER = Ic2Blocks.register("classic_canner", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityClassicCanner.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        COMPRESSOR = Ic2Blocks.register("compressor", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityCompressor.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        ELECTRIC_FURNACE = Ic2Blocks.register("electric_furnace", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityElectricFurnace.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
        EXTRACTOR = Ic2Blocks.register("extractor", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityExtractor.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        IRON_FURNACE = Ic2Blocks.register("iron_furnace", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(5.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityIronFurnace.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, false));
        MACERATOR = Ic2Blocks.register("macerator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityMacerator.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        RECYCLER = Ic2Blocks.register("recycler", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityRecycler.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        SOLID_CANNER = Ic2Blocks.register("solid_canner", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySolidCanner.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        BLAST_FURNACE = Ic2Blocks.register("blast_furnace", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityBlastFurnace.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
        BLOCK_CUTTER = Ic2Blocks.register("block_cutter", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityBlockCutter.class, true, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
        CENTRIFUGE = Ic2Blocks.register("centrifuge", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityCentrifuge.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        FERMENTER = Ic2Blocks.register("fermenter", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityFermenter.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
        INDUCTION_FURNACE = Ic2Blocks.register("induction_furnace", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityInduction.class, true, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
        METAL_FORMER = Ic2Blocks.register("metal_former", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityMetalFormer.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        ORE_WASHING_PLANT = Ic2Blocks.register("ore_washing_plant", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityOreWashing.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        ADVANCED_MINER = Ic2Blocks.register("advanced_miner", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityAdvMiner.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
        CROP_HARVESTER = Ic2Blocks.register("crop_harvester", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityCropHarvester.class, false, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        CROPMATRON = Ic2Blocks.register("cropmatron", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityCropmatron.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        CLASSIC_CROPMATRON = Ic2Blocks.register("classic_cropmatron", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityClassicCropmatron.class, false, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        MINER = Ic2Blocks.register("miner", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityMiner.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
        MASS_FABRICATOR = Ic2Blocks.register("mass_fabricator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityMassFabricator.class, true, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
        CLASSIC_MASS_FABRICATOR = Ic2Blocks.register("classic_mass_fabricator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityClassicMassFabricator.class, true, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
        UU_ASSEMBLY_BENCH = Ic2Blocks.register("uu_assembly_bench", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityAssemblyBench.class, true, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
        MATTER_GENERATOR = Ic2Blocks.register("matter_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityMatter.class, true, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
        PATTERN_STORAGE = Ic2Blocks.register("pattern_storage", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityPatternStorage.class, false, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
        REPLICATOR = Ic2Blocks.register("replicator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityReplicator.class, true, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
        UU_SCANNER = Ic2Blocks.register("uu_scanner", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityScanner.class, true, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
        ENERGY_O_MAT = Ic2Blocks.register("energy_o_mat", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(-1.0f, 3600000.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityEnergyOMat.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.allFacings, false));
        PERSONAL_CHEST = Ic2Blocks.register("personal_chest", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(-1.0f, 3600000.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityPersonalChest.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, false));
        TRADE_O_MAT = Ic2Blocks.register("trade_o_mat", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(-1.0f, 3600000.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTradeOMat.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, false));
        cableSettings = BlockBehaviour.Properties.of().strength(0.5f, 5.0f).sound(SoundType.METAL);
        insulatedCableSettings = BlockBehaviour.Properties.of().strength(0.5f, 5.0f).sound(SoundType.WOOL);
        COPPER_FOAM_CABLE = Ic2Blocks.register("copper_foam_cable", FoamCableBlock.create(cableSettings, CableType.copper, 0));
        COPPER_CABLE = Ic2Blocks.register("copper_cable", CableBlock.create(cableSettings, CableType.copper, 0, COPPER_FOAM_CABLE));
        INSULATED_COPPER_FOAM_CABLE = Ic2Blocks.register("insulated_copper_foam_cable", FoamCableBlock.create(insulatedCableSettings, CableType.copper, 1));
        INSULATED_COPPER_CABLE = Ic2Blocks.register("insulated_copper_cable", CableBlock.create(insulatedCableSettings, CableType.copper, 1, INSULATED_COPPER_FOAM_CABLE));
        GLASS_FIBRE_FOAM_CABLE = Ic2Blocks.register("glass_fibre_foam_cable", FoamCableBlock.create(BlockBehaviour.Properties.of().strength(0.5f, 5.0f).sound(SoundType.GLASS), CableType.glass, 0));
        GLASS_FIBRE_CABLE = Ic2Blocks.register("glass_fibre_cable", CableBlock.create(BlockBehaviour.Properties.of().strength(0.5f, 5.0f).sound(SoundType.GLASS), CableType.glass, 0, GLASS_FIBRE_FOAM_CABLE));
        GOLD_FOAM_CABLE = Ic2Blocks.register("gold_foam_cable", FoamCableBlock.create(cableSettings, CableType.gold, 0));
        GOLD_CABLE = Ic2Blocks.register("gold_cable", CableBlock.create(cableSettings, CableType.gold, 0, GOLD_FOAM_CABLE));
        INSULATED_GOLD_FOAM_CABLE = Ic2Blocks.register("insulated_gold_foam_cable", FoamCableBlock.create(insulatedCableSettings, CableType.gold, 1));
        INSULATED_GOLD_CABLE = Ic2Blocks.register("insulated_gold_cable", CableBlock.create(insulatedCableSettings, CableType.gold, 1, INSULATED_GOLD_FOAM_CABLE));
        DOUBLE_INSULATED_GOLD_FOAM_CABLE = Ic2Blocks.register("double_insulated_gold_foam_cable", FoamCableBlock.create(insulatedCableSettings, CableType.gold, 2));
        DOUBLE_INSULATED_GOLD_CABLE = Ic2Blocks.register("double_insulated_gold_cable", CableBlock.create(insulatedCableSettings, CableType.gold, 2, DOUBLE_INSULATED_GOLD_FOAM_CABLE));
        IRON_FOAM_CABLE = Ic2Blocks.register("iron_foam_cable", FoamCableBlock.create(cableSettings, CableType.iron, 0));
        IRON_CABLE = Ic2Blocks.register("iron_cable", CableBlock.create(cableSettings, CableType.iron, 0, IRON_FOAM_CABLE));
        INSULATED_IRON_FOAM_CABLE = Ic2Blocks.register("insulated_iron_foam_cable", FoamCableBlock.create(insulatedCableSettings, CableType.iron, 1));
        INSULATED_IRON_CABLE = Ic2Blocks.register("insulated_iron_cable", CableBlock.create(insulatedCableSettings, CableType.iron, 1, INSULATED_IRON_FOAM_CABLE));
        DOUBLE_INSULATED_IRON_FOAM_CABLE = Ic2Blocks.register("double_insulated_iron_foam_cable", FoamCableBlock.create(insulatedCableSettings, CableType.iron, 2));
        DOUBLE_INSULATED_IRON_CABLE = Ic2Blocks.register("double_insulated_iron_cable", CableBlock.create(insulatedCableSettings, CableType.iron, 2, DOUBLE_INSULATED_IRON_FOAM_CABLE));
        TRIPLE_INSULATED_IRON_FOAM_CABLE = Ic2Blocks.register("triple_insulated_iron_foam_cable", FoamCableBlock.create(insulatedCableSettings, CableType.iron, 3));
        TRIPLE_INSULATED_IRON_CABLE = Ic2Blocks.register("triple_insulated_iron_cable", CableBlock.create(insulatedCableSettings, CableType.iron, 3, TRIPLE_INSULATED_IRON_FOAM_CABLE));
        TIN_FOAM_CABLE = Ic2Blocks.register("tin_foam_cable", FoamCableBlock.create(cableSettings, CableType.tin, 0));
        TIN_CABLE = Ic2Blocks.register("tin_cable", CableBlock.create(cableSettings, CableType.tin, 0, TIN_FOAM_CABLE));
        INSULATED_TIN_FOAM_CABLE = Ic2Blocks.register("insulated_tin_foam_cable", FoamCableBlock.create(insulatedCableSettings, CableType.tin, 1));
        INSULATED_TIN_CABLE = Ic2Blocks.register("insulated_tin_cable", CableBlock.create(insulatedCableSettings, CableType.tin, 1, INSULATED_TIN_FOAM_CABLE));
        DETECTOR_FOAM_CABLE = Ic2Blocks.register("detector_foam_cable", DetectorFoamCableBlock.create(cableSettings));
        DETECTOR_CABLE = Ic2Blocks.register("detector_cable", DetectorCableBlock.create(cableSettings, DETECTOR_FOAM_CABLE));
        SPLITTER_FOAM_CABLE = Ic2Blocks.register("splitter_foam_cable", SplitterFoamCableBlock.create(cableSettings));
        SPLITTER_CABLE = Ic2Blocks.register("splitter_cable", SplitterCableBlock.create(cableSettings, SPLITTER_FOAM_CABLE));
        BATBOX_CHARGEPAD = Ic2Blocks.register("batbox_chargepad", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL).noOcclusion(), TileEntityChargepadBatBox.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.downSideFacings, true));
        CESU_CHARGEPAD = Ic2Blocks.register("cesu_chargepad", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL).noOcclusion(), TileEntityChargepadCESU.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.downSideFacings, true));
        MFE_CHARGEPAD = Ic2Blocks.register("mfe_chargepad", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL).noOcclusion(), TileEntityChargepadMFE.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.downSideFacings, true));
        MFSU_CHARGEPAD = Ic2Blocks.register("mfsu_chargepad", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL).noOcclusion(), TileEntityChargepadMFSU.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.downSideFacings, true));
        BATBOX = Ic2Blocks.register("batbox", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityElectricBatBox.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.allFacings, true));
        CESU = Ic2Blocks.register("cesu", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityElectricCESU.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.allFacings, true));
        MFE = Ic2Blocks.register("mfe", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityElectricMFE.class, false, Ic2TileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
        CLASSIC_MFE = Ic2Blocks.register("classic_mfe", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityElectricMFE.TileEntityElectricClassicMFE.class, false, Ic2TileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
        MFSU = Ic2Blocks.register("mfsu", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityElectricMFSU.class, false, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.allFacings, true));
        CLASSIC_MFSU = Ic2Blocks.register("classic_mfsu", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityElectricMFSU.TileEntityElectricClassicMFSU.class, false, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.allFacings, true));
        ELECTROLYZER = Ic2Blocks.register("electrolyzer", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityElectrolyzer.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        CLASSIC_ELECTROLYZER = Ic2Blocks.register("classic_electrolyzer", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityClassicElectrolyzer.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.horizontalFacings, true));
        LV_TRANSFORMER = Ic2Blocks.register("lv_transformer", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTransformerLV.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.allFacings, true));
        MV_TRANSFORMER = Ic2Blocks.register("mv_transformer", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTransformerMV.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
        HV_TRANSFORMER = Ic2Blocks.register("hv_transformer", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTransformerHV.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
        EV_TRANSFORMER = Ic2Blocks.register("ev_transformer", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTransformerEV.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
        TANK = Ic2Blocks.register("tank", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityTank.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
        CHUNK_LOADER = Ic2Blocks.register("chunk_loader", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityChunkloader.class, true, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
        CREATIVE_GENERATOR = Ic2Blocks.register("creative_generator", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(-1.0f, Float.POSITIVE_INFINITY).sound(SoundType.METAL), TileEntityCreativeGenerator.class, true, Ic2TileEntityBlock.DefaultDrop.None, Util.noFacings, false));
        STEAM_REPRESSURIZER = Ic2Blocks.register("steam_repressurizer", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntitySteamRepressurizer.class, true, Ic2TileEntityBlock.DefaultDrop.Machine, Util.noFacings, true));
        WEIGHTED_FLUID_DISTRIBUTOR = Ic2Blocks.register("weighted_fluid_distributor", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityWeightedFluidDistributor.class, false, Ic2TileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
        WEIGHTED_ITEM_DISTRIBUTOR = Ic2Blocks.register("weighted_item_distributor", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityWeightedItemDistributor.class, false, Ic2TileEntityBlock.DefaultDrop.Machine, Util.allFacings, true));
        RCI_RSH = Ic2Blocks.register("rci_rsh", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityRCI_RSH.class, true, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.allFacings, true));
        RCI_LZH = Ic2Blocks.register("rci_lzh", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityRCI_LZH.class, true, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.allFacings, true));
        cropSettings = BlockBehaviour.Properties.of().strength(0.8f, 0.2f).sound(SoundType.CROP).noCollission();
        CROP_STICK = Ic2Blocks.register("crop_stick", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.none));
        WEED_CROP = Ic2Blocks.register("weed_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.weed));
        WHEAT_CROP = Ic2Blocks.register("wheat_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.wheat));
        CARROTS_CROP = Ic2Blocks.register("carrots_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.carrots));
        POTATO_CROP = Ic2Blocks.register("potato_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.potato));
        BEETROOTS_CROP = Ic2Blocks.register("beetroots_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.beetroots));
        PUMPKIN_CROP = Ic2Blocks.register("pumpkin_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.pumpkin));
        MELON_CROP = Ic2Blocks.register("melon_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.melon));
        DANDELION_CROP = Ic2Blocks.register("dandelion_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.dandelion));
        POPPY_CROP = Ic2Blocks.register("poppy_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.poppy));
        BLACKTHORN_CROP = Ic2Blocks.register("blackthorn_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.blackthorn));
        TULIP_CROP = Ic2Blocks.register("tulip_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.tulip));
        CYAZINT_CROP = Ic2Blocks.register("cyazint_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.cyazint));
        VENOMILIA_CROP = Ic2Blocks.register("venomilia_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.venomilia));
        REED_CROP = Ic2Blocks.register("reed_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.reed));
        STICKY_REED_CROP = Ic2Blocks.register("sticky_reed_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.stickyReed));
        COCOA_CROP = Ic2Blocks.register("cocoa_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.cocoa));
        FLAX_CROP = Ic2Blocks.register("flax_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.flax));
        RED_MUSHROOM_CROP = Ic2Blocks.register("red_mushroom_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.redMushroom));
        BROWN_MUSHROOM_CROP = Ic2Blocks.register("brown_mushroom_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.brownMushroom));
        NETHER_WART_CROP = Ic2Blocks.register("nether_wart_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.netherWart));
        TERRA_WART_CROP = Ic2Blocks.register("terra_wart_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.terraWart));
        OAK_SAPLING_CROP = Ic2Blocks.register("oak_sapling_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.oakSapling));
        SPRUCE_SAPLING_CROP = Ic2Blocks.register("spruce_sapling_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.spruceSapling));
        BIRCH_SAPLING_CROP = Ic2Blocks.register("birch_sapling_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.birchSapling));
        JUNGLE_SAPLING_CROP = Ic2Blocks.register("jungle_sapling_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.jungleSapling));
        ACACIA_SAPLING_CROP = Ic2Blocks.register("acacia_sapling_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.acaciaSapling));
        DARK_OAK_SAPLING_CROP = Ic2Blocks.register("dark_oak_sapling_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.darkOakSapling));
        FERRU_CROP = Ic2Blocks.register("ferru_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.ferru));
        CYPRIUM_CROP = Ic2Blocks.register("cyprium_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.cyprium));
        STAGNIUM_CROP = Ic2Blocks.register("stagnium_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.stagnium));
        PLUMBISCUS_CROP = Ic2Blocks.register("plumbiscus_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.plumbiscus));
        AURELIA_CROP = Ic2Blocks.register("aurelia_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.aurelia));
        SHINING_CROP = Ic2Blocks.register("shining_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.shining));
        RED_WHEAT_CROP = Ic2Blocks.register("red_wheat_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.redWheat));
        COFFEE_CROP = Ic2Blocks.register("coffee_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.coffee));
        HOPS_CROP = Ic2Blocks.register("hops_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.hops));
        EATING_PLANT_CROP = Ic2Blocks.register("eating_plant_crop", Ic2TileEntityBlock.create(cropSettings, TileEntityCrop.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false, Ic2CropType.eatingPlant));
        INDUSTRIAL_WORKBENCH = Ic2Blocks.register("industrial_workbench", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityIndustrialWorkbench.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.horizontalFacings, true));
        BATCH_CRAFTER = Ic2Blocks.register("batch_crafter", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 10.0f).requiresCorrectToolForDrops().sound(SoundType.METAL), TileEntityBatchCrafter.class, true, Ic2TileEntityBlock.DefaultDrop.AdvMachine, Util.horizontalFacings, true));
        WOODEN_STORAGE_BOX = Ic2Blocks.register("wooden_storage_box", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(1.0f, 10.0f).sound(SoundType.WOOD), TileEntityWoodenStorageBox.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false));
        IRON_STORAGE_BOX = Ic2Blocks.register("iron_storage_box", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(1.0f, 15.0f).sound(SoundType.METAL), TileEntityIronStorageBox.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false));
        BRONZE_STORAGE_BOX = Ic2Blocks.register("bronze_storage_box", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(1.0f, 15.0f).sound(SoundType.METAL), TileEntityBronzeStorageBox.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false));
        STEEL_STORAGE_BOX = Ic2Blocks.register("steel_storage_box", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(2.0f, 20.0f).sound(SoundType.METAL), TileEntitySteelStorageBox.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false));
        IRIDIUM_STORAGE_BOX = Ic2Blocks.register("iridium_storage_box", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(3.0f, 100.0f).sound(SoundType.METAL), TileEntityIridiumStorageBox.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false));
        BRONZE_TANK = Ic2Blocks.register("bronze_tank", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(3.0f, 15.0f).sound(SoundType.METAL), TileEntityBronzeTank.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false));
        IRON_TANK = Ic2Blocks.register("iron_tank", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(3.0f, 15.0f).sound(SoundType.METAL), TileEntityIronTank.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false));
        STEEL_TANK = Ic2Blocks.register("steel_tank", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(4.0f, 20.0f).sound(SoundType.METAL), TileEntitySteelTank.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false));
        IRIDIUM_TANK = Ic2Blocks.register("iridium_tank", Ic2TileEntityBlock.create(BlockBehaviour.Properties.of().strength(5.0f, 100.0f).sound(SoundType.METAL), TileEntityIridiumTank.class, false, Ic2TileEntityBlock.DefaultDrop.Self, Util.noFacings, false));
    }
}

