/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.core.BlockPos
 *  net.minecraft.resources.ResourceLocation
 *  net.minecraft.world.level.block.Block
 *  net.minecraft.world.level.block.entity.BlockEntity
 *  net.minecraft.world.level.block.entity.BlockEntityType
 *  net.minecraft.world.level.block.state.BlockState
 */
package ic2.core.ref;

import ic2.core.IC2;
import ic2.core.block.generator.tileentity.TileEntityCreativeGenerator;
import ic2.core.block.generator.tileentity.TileEntityGenerator;
import ic2.core.block.generator.tileentity.TileEntityGeoGenerator;
import ic2.core.block.generator.tileentity.TileEntityKineticGenerator;
import ic2.core.block.generator.tileentity.TileEntityRTGenerator;
import ic2.core.block.generator.tileentity.TileEntitySemifluidGenerator;
import ic2.core.block.generator.tileentity.TileEntitySolarGenerator;
import ic2.core.block.generator.tileentity.TileEntityStirlingGenerator;
import ic2.core.block.generator.tileentity.TileEntityWaterGenerator;
import ic2.core.block.generator.tileentity.TileEntityWindGenerator;
import ic2.core.block.heatgenerator.tileentity.TileEntityElectricHeatGenerator;
import ic2.core.block.heatgenerator.tileentity.TileEntityFluidHeatGenerator;
import ic2.core.block.heatgenerator.tileentity.TileEntityRTHeatGenerator;
import ic2.core.block.heatgenerator.tileentity.TileEntitySolidHeatGenerator;
import ic2.core.block.kineticgenerator.tileentity.TileEntityElectricKineticGenerator;
import ic2.core.block.kineticgenerator.tileentity.TileEntityManualKineticGenerator;
import ic2.core.block.kineticgenerator.tileentity.TileEntitySteamKineticGenerator;
import ic2.core.block.kineticgenerator.tileentity.TileEntityStirlingKineticGenerator;
import ic2.core.block.kineticgenerator.tileentity.TileEntityWaterKineticGenerator;
import ic2.core.block.kineticgenerator.tileentity.TileEntityWindKineticGenerator;
import ic2.core.block.machine.tileentity.TileEntityAdvMiner;
import ic2.core.block.machine.tileentity.TileEntityAssemblyBench;
import ic2.core.block.machine.tileentity.TileEntityBatchCrafter;
import ic2.core.block.machine.tileentity.TileEntityBlastFurnace;
import ic2.core.block.machine.tileentity.TileEntityBlockCutter;
import ic2.core.block.machine.tileentity.TileEntityBridgeNuke;
import ic2.core.block.machine.tileentity.TileEntityCanner;
import ic2.core.block.machine.tileentity.TileEntityCentrifuge;
import ic2.core.block.machine.tileentity.TileEntityChunkloader;
import ic2.core.block.machine.tileentity.TileEntityClassicCanner;
import ic2.core.block.machine.tileentity.TileEntityClassicCropmatron;
import ic2.core.block.machine.tileentity.TileEntityClassicElectrolyzer;
import ic2.core.block.machine.tileentity.TileEntityClassicMassFabricator;
import ic2.core.block.machine.tileentity.TileEntityCompressor;
import ic2.core.block.machine.tileentity.TileEntityCondenser;
import ic2.core.block.machine.tileentity.TileEntityCropHarvester;
import ic2.core.block.machine.tileentity.TileEntityCropmatron;
import ic2.core.block.machine.tileentity.TileEntityElectricFurnace;
import ic2.core.block.machine.tileentity.TileEntityElectrolyzer;
import ic2.core.block.machine.tileentity.TileEntityExtractor;
import ic2.core.block.machine.tileentity.TileEntityFermenter;
import ic2.core.block.machine.tileentity.TileEntityFluidBottler;
import ic2.core.block.machine.tileentity.TileEntityFluidDistributor;
import ic2.core.block.machine.tileentity.TileEntityFluidRegulator;
import ic2.core.block.machine.tileentity.TileEntityITnt;
import ic2.core.block.machine.tileentity.TileEntityInduction;
import ic2.core.block.machine.tileentity.TileEntityIndustrialWorkbench;
import ic2.core.block.machine.tileentity.TileEntityIronFurnace;
import ic2.core.block.machine.tileentity.TileEntityItemBuffer;
import ic2.core.block.machine.tileentity.TileEntityLiquidHeatExchanger;
import ic2.core.block.machine.tileentity.TileEntityMacerator;
import ic2.core.block.machine.tileentity.TileEntityMagnetizer;
import ic2.core.block.machine.tileentity.TileEntityMassFabricator;
import ic2.core.block.machine.tileentity.TileEntityMatter;
import ic2.core.block.machine.tileentity.TileEntityMetalFormer;
import ic2.core.block.machine.tileentity.TileEntityMiner;
import ic2.core.block.machine.tileentity.TileEntityNuke;
import ic2.core.block.machine.tileentity.TileEntityOreWashing;
import ic2.core.block.machine.tileentity.TileEntityPatternStorage;
import ic2.core.block.machine.tileentity.TileEntityPump;
import ic2.core.block.machine.tileentity.TileEntityRecycler;
import ic2.core.block.machine.tileentity.TileEntityReplicator;
import ic2.core.block.machine.tileentity.TileEntityScanner;
import ic2.core.block.machine.tileentity.TileEntitySolarDestiller;
import ic2.core.block.machine.tileentity.TileEntitySolidCanner;
import ic2.core.block.machine.tileentity.TileEntitySortingMachine;
import ic2.core.block.machine.tileentity.TileEntitySteamGenerator;
import ic2.core.block.machine.tileentity.TileEntitySteamRepressurizer;
import ic2.core.block.machine.tileentity.TileEntityTank;
import ic2.core.block.machine.tileentity.TileEntityTeleporter;
import ic2.core.block.machine.tileentity.TileEntityTerra;
import ic2.core.block.machine.tileentity.TileEntityTesla;
import ic2.core.block.machine.tileentity.TileEntityWeightedFluidDistributor;
import ic2.core.block.machine.tileentity.TileEntityWeightedItemDistributor;
import ic2.core.block.personal.TileEntityEnergyOMat;
import ic2.core.block.personal.TileEntityPersonalChest;
import ic2.core.block.personal.TileEntityTradeOMat;
import ic2.core.block.reactor.tileentity.TileEntityNuclearReactorElectric;
import ic2.core.block.reactor.tileentity.TileEntityRCI_LZH;
import ic2.core.block.reactor.tileentity.TileEntityRCI_RSH;
import ic2.core.block.reactor.tileentity.TileEntityReactorAccessHatch;
import ic2.core.block.reactor.tileentity.TileEntityReactorChamberElectric;
import ic2.core.block.reactor.tileentity.TileEntityReactorFluidPort;
import ic2.core.block.reactor.tileentity.TileEntityReactorRedstonePort;
import ic2.core.block.storage.box.TileEntityBronzeStorageBox;
import ic2.core.block.storage.box.TileEntityIridiumStorageBox;
import ic2.core.block.storage.box.TileEntityIronStorageBox;
import ic2.core.block.storage.box.TileEntitySteelStorageBox;
import ic2.core.block.storage.box.TileEntityWoodenStorageBox;
import ic2.core.block.storage.tank.TileEntityBronzeTank;
import ic2.core.block.storage.tank.TileEntityIridiumTank;
import ic2.core.block.storage.tank.TileEntityIronTank;
import ic2.core.block.storage.tank.TileEntitySteelTank;
import ic2.core.block.tileentity.Ic2SignBlockEntity;
import ic2.core.block.tileentity.TileEntityWall;
import ic2.core.block.wiring.tileentity.TileEntityChargepadBatBox;
import ic2.core.block.wiring.tileentity.TileEntityChargepadCESU;
import ic2.core.block.wiring.tileentity.TileEntityChargepadMFE;
import ic2.core.block.wiring.tileentity.TileEntityChargepadMFSU;
import ic2.core.block.wiring.tileentity.TileEntityElectricBatBox;
import ic2.core.block.wiring.tileentity.TileEntityElectricCESU;
import ic2.core.block.wiring.tileentity.TileEntityElectricMFE;
import ic2.core.block.wiring.tileentity.TileEntityElectricMFSU;
import ic2.core.block.wiring.tileentity.TileEntityTransformerEV;
import ic2.core.block.wiring.tileentity.TileEntityTransformerHV;
import ic2.core.block.wiring.tileentity.TileEntityTransformerLV;
import ic2.core.block.wiring.tileentity.TileEntityTransformerMV;
import ic2.core.crop.TileEntityCrop;
import ic2.core.ref.Ic2Blocks;
import java.util.HashMap;
import java.util.Map;
import java.util.function.BiFunction;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;

public final class Ic2BlockEntities {
    public static final BlockEntityType<Ic2SignBlockEntity> SIGN = Ic2BlockEntities.register("sign", (BiFunction<BlockPos, BlockState, Ic2SignBlockEntity>)Ic2SignBlockEntity::new, Ic2Blocks.RUBBER_SIGN, Ic2Blocks.RUBBER_WALL_SIGN);
    public static final BlockEntityType<TileEntityWall> WALL = Ic2BlockEntities.register("wall", (BiFunction<BlockPos, BlockState, TileEntityWall>)TileEntityWall::new, Ic2Blocks.OBSCURED_WALL);
    public static final BlockEntityType<TileEntityITnt> ITNT = Ic2BlockEntities.register("itnt", (BiFunction<BlockPos, BlockState, TileEntityITnt>)TileEntityITnt::new, Ic2Blocks.ITNT);
    public static final BlockEntityType<TileEntityNuke> NUKE = Ic2BlockEntities.register("nuke", (BiFunction<BlockPos, BlockState, TileEntityNuke>)TileEntityNuke::new, Ic2Blocks.NUKE);
    public static final BlockEntityType<TileEntityBridgeNuke.TileEntityClassicNuke> CLASSIC_NUKE = Ic2BlockEntities.register("classic_nuke", (BiFunction<BlockPos, BlockState, TileEntityBridgeNuke.TileEntityClassicNuke>)TileEntityBridgeNuke.TileEntityClassicNuke::new, Ic2Blocks.CLASSIC_NUKE);
    public static final BlockEntityType<TileEntityGenerator> GENERATOR = Ic2BlockEntities.register("generator", (BiFunction<BlockPos, BlockState, TileEntityGenerator>)TileEntityGenerator::new, Ic2Blocks.GENERATOR);
    public static final BlockEntityType<TileEntityGeoGenerator> GEO_GENERATOR = Ic2BlockEntities.register("geo_generator", (BiFunction<BlockPos, BlockState, TileEntityGeoGenerator>)TileEntityGeoGenerator::new, Ic2Blocks.GEO_GENERATOR);
    public static final BlockEntityType<TileEntityKineticGenerator> KINETIC_GENERATOR = Ic2BlockEntities.register("kinetic_generator", (BiFunction<BlockPos, BlockState, TileEntityKineticGenerator>)TileEntityKineticGenerator::new, Ic2Blocks.KINETIC_GENERATOR);
    public static final BlockEntityType<TileEntityRTGenerator> RT_GENERATOR = Ic2BlockEntities.register("rt_generator", (BiFunction<BlockPos, BlockState, TileEntityRTGenerator>)TileEntityRTGenerator::new, Ic2Blocks.RT_GENERATOR);
    public static final BlockEntityType<TileEntitySemifluidGenerator> SEMIFLUID_GENERATOR = Ic2BlockEntities.register("semifluid_generator", (BiFunction<BlockPos, BlockState, TileEntitySemifluidGenerator>)TileEntitySemifluidGenerator::new, Ic2Blocks.SEMIFLUID_GENERATOR);
    public static final BlockEntityType<TileEntitySolarGenerator> SOLAR_GENERATOR = Ic2BlockEntities.register("solar_generator", (BiFunction<BlockPos, BlockState, TileEntitySolarGenerator>)TileEntitySolarGenerator::new, Ic2Blocks.SOLAR_GENERATOR);
    public static final BlockEntityType<TileEntityStirlingGenerator> STIRLING_GENERATOR = Ic2BlockEntities.register("stirling_generator", (BiFunction<BlockPos, BlockState, TileEntityStirlingGenerator>)TileEntityStirlingGenerator::new, Ic2Blocks.STIRLING_GENERATOR);
    public static final BlockEntityType<TileEntityWaterGenerator> WATER_GENERATOR = Ic2BlockEntities.register("water_generator", (BiFunction<BlockPos, BlockState, TileEntityWaterGenerator>)TileEntityWaterGenerator::new, Ic2Blocks.WATER_GENERATOR);
    public static final BlockEntityType<TileEntityWindGenerator> WIND_GENERATOR = Ic2BlockEntities.register("wind_generator", (BiFunction<BlockPos, BlockState, TileEntityWindGenerator>)TileEntityWindGenerator::new, Ic2Blocks.WIND_GENERATOR);
    public static final BlockEntityType<TileEntityElectricHeatGenerator> ELECTRIC_HEAT_GENERATOR = Ic2BlockEntities.register("electric_heat_generator", (BiFunction<BlockPos, BlockState, TileEntityElectricHeatGenerator>)TileEntityElectricHeatGenerator::new, Ic2Blocks.ELECTRIC_HEAT_GENERATOR);
    public static final BlockEntityType<TileEntityFluidHeatGenerator> FLUID_HEAT_GENERATOR = Ic2BlockEntities.register("fluid_heat_generator", (BiFunction<BlockPos, BlockState, TileEntityFluidHeatGenerator>)TileEntityFluidHeatGenerator::new, Ic2Blocks.FLUID_HEAT_GENERATOR);
    public static final BlockEntityType<TileEntityRTHeatGenerator> RT_HEAT_GENERATOR = Ic2BlockEntities.register("rt_heat_generator", (BiFunction<BlockPos, BlockState, TileEntityRTHeatGenerator>)TileEntityRTHeatGenerator::new, Ic2Blocks.RT_HEAT_GENERATOR);
    public static final BlockEntityType<TileEntitySolidHeatGenerator> SOLID_HEAT_GENERATOR = Ic2BlockEntities.register("solid_heat_generator", (BiFunction<BlockPos, BlockState, TileEntitySolidHeatGenerator>)TileEntitySolidHeatGenerator::new, Ic2Blocks.SOLID_HEAT_GENERATOR);
    public static final BlockEntityType<TileEntityElectricKineticGenerator> ELECTRIC_KINETIC_GENERATOR = Ic2BlockEntities.register("electric_kinetic_generator", (BiFunction<BlockPos, BlockState, TileEntityElectricKineticGenerator>)TileEntityElectricKineticGenerator::new, Ic2Blocks.ELECTRIC_KINETIC_GENERATOR);
    public static final BlockEntityType<TileEntityManualKineticGenerator> MANUAL_KINETIC_GENERATOR = Ic2BlockEntities.register("manual_kinetic_generator", (BiFunction<BlockPos, BlockState, TileEntityManualKineticGenerator>)TileEntityManualKineticGenerator::new, Ic2Blocks.MANUAL_KINETIC_GENERATOR);
    public static final BlockEntityType<TileEntitySteamKineticGenerator> STEAM_KINETIC_GENERATOR = Ic2BlockEntities.register("steam_kinetic_generator", (BiFunction<BlockPos, BlockState, TileEntitySteamKineticGenerator>)TileEntitySteamKineticGenerator::new, Ic2Blocks.STEAM_KINETIC_GENERATOR);
    public static final BlockEntityType<TileEntityStirlingKineticGenerator> STIRLING_KINETIC_GENERATOR = Ic2BlockEntities.register("stirling_kinetic_generator", (BiFunction<BlockPos, BlockState, TileEntityStirlingKineticGenerator>)TileEntityStirlingKineticGenerator::new, Ic2Blocks.STIRLING_KINETIC_GENERATOR);
    public static final BlockEntityType<TileEntityWaterKineticGenerator> WATER_KINETIC_GENERATOR = Ic2BlockEntities.register("water_kinetic_generator", (BiFunction<BlockPos, BlockState, TileEntityWaterKineticGenerator>)TileEntityWaterKineticGenerator::new, Ic2Blocks.WATER_KINETIC_GENERATOR);
    public static final BlockEntityType<TileEntityWindKineticGenerator> WIND_KINETIC_GENERATOR = Ic2BlockEntities.register("wind_kinetic_generator", (BiFunction<BlockPos, BlockState, TileEntityWindKineticGenerator>)TileEntityWindKineticGenerator::new, Ic2Blocks.WIND_KINETIC_GENERATOR);
    public static final BlockEntityType<TileEntityNuclearReactorElectric> NUCLEAR_REACTOR = Ic2BlockEntities.register("nuclear_reactor", (BiFunction<BlockPos, BlockState, TileEntityNuclearReactorElectric>)TileEntityNuclearReactorElectric::new, Ic2Blocks.NUCLEAR_REACTOR);
    public static final BlockEntityType<TileEntityReactorAccessHatch> REACTOR_ACCESS_HATCH = Ic2BlockEntities.register("reactor_access_hatch", (BiFunction<BlockPos, BlockState, TileEntityReactorAccessHatch>)TileEntityReactorAccessHatch::new, Ic2Blocks.REACTOR_ACCESS_HATCH);
    public static final BlockEntityType<TileEntityReactorChamberElectric> REACTOR_CHAMBER = Ic2BlockEntities.register("reactor_chamber", (BiFunction<BlockPos, BlockState, TileEntityReactorChamberElectric>)TileEntityReactorChamberElectric::new, Ic2Blocks.REACTOR_CHAMBER);
    public static final BlockEntityType<TileEntityReactorFluidPort> REACTOR_FLUID_PORT = Ic2BlockEntities.register("reactor_fluid_port", (BiFunction<BlockPos, BlockState, TileEntityReactorFluidPort>)TileEntityReactorFluidPort::new, Ic2Blocks.REACTOR_FLUID_PORT);
    public static final BlockEntityType<TileEntityReactorRedstonePort> REACTOR_REDSTONE_PORT = Ic2BlockEntities.register("reactor_redstone_port", (BiFunction<BlockPos, BlockState, TileEntityReactorRedstonePort>)TileEntityReactorRedstonePort::new, Ic2Blocks.REACTOR_REDSTONE_PORT);
    public static final BlockEntityType<TileEntityCondenser> CONDENSER = Ic2BlockEntities.register("condenser", (BiFunction<BlockPos, BlockState, TileEntityCondenser>)TileEntityCondenser::new, Ic2Blocks.CONDENSER);
    public static final BlockEntityType<TileEntityFluidBottler> FLUID_BOTTLER = Ic2BlockEntities.register("fluid_bottler", (BiFunction<BlockPos, BlockState, TileEntityFluidBottler>)TileEntityFluidBottler::new, Ic2Blocks.FLUID_BOTTLER);
    public static final BlockEntityType<TileEntityFluidDistributor> FLUID_DISTRIBUTOR = Ic2BlockEntities.register("fluid_distributor", (BiFunction<BlockPos, BlockState, TileEntityFluidDistributor>)TileEntityFluidDistributor::new, Ic2Blocks.FLUID_DISTRIBUTOR);
    public static final BlockEntityType<TileEntityFluidRegulator> FLUID_REGULATOR = Ic2BlockEntities.register("fluid_regulator", (BiFunction<BlockPos, BlockState, TileEntityFluidRegulator>)TileEntityFluidRegulator::new, Ic2Blocks.FLUID_REGULATOR);
    public static final BlockEntityType<TileEntityLiquidHeatExchanger> LIQUID_HEAT_EXCHANGER = Ic2BlockEntities.register("liquid_heat_exchanger", (BiFunction<BlockPos, BlockState, TileEntityLiquidHeatExchanger>)TileEntityLiquidHeatExchanger::new, Ic2Blocks.LIQUID_HEAT_EXCHANGER);
    public static final BlockEntityType<TileEntityPump> PUMP = Ic2BlockEntities.register("pump", (BiFunction<BlockPos, BlockState, TileEntityPump>)TileEntityPump::new, Ic2Blocks.PUMP);
    public static final BlockEntityType<TileEntitySolarDestiller> SOLAR_DISTILLER = Ic2BlockEntities.register("solar_distiller", (BiFunction<BlockPos, BlockState, TileEntitySolarDestiller>)TileEntitySolarDestiller::new, Ic2Blocks.SOLAR_DISTILLER);
    public static final BlockEntityType<TileEntitySteamGenerator> STEAM_GENERATOR = Ic2BlockEntities.register("steam_generator", (BiFunction<BlockPos, BlockState, TileEntitySteamGenerator>)TileEntitySteamGenerator::new, Ic2Blocks.STEAM_GENERATOR);
    public static final BlockEntityType<TileEntityItemBuffer> ITEM_BUFFER = Ic2BlockEntities.register("item_buffer", (BiFunction<BlockPos, BlockState, TileEntityItemBuffer>)TileEntityItemBuffer::new, Ic2Blocks.ITEM_BUFFER);
    public static final BlockEntityType<TileEntityMagnetizer> MAGNETIZER = Ic2BlockEntities.register("magnetizer", (BiFunction<BlockPos, BlockState, TileEntityMagnetizer>)TileEntityMagnetizer::new, Ic2Blocks.MAGNETIZER);
    public static final BlockEntityType<TileEntitySortingMachine> SORTING_MACHINE = Ic2BlockEntities.register("sorting_machine", (BiFunction<BlockPos, BlockState, TileEntitySortingMachine>)TileEntitySortingMachine::new, Ic2Blocks.SORTING_MACHINE);
    public static final BlockEntityType<TileEntityTeleporter> TELEPORTER = Ic2BlockEntities.register("teleporter", (BiFunction<BlockPos, BlockState, TileEntityTeleporter>)TileEntityTeleporter::new, Ic2Blocks.TELEPORTER);
    public static final BlockEntityType<TileEntityTerra> TERRAFORMER = Ic2BlockEntities.register("terraformer", (BiFunction<BlockPos, BlockState, TileEntityTerra>)TileEntityTerra::new, Ic2Blocks.TERRAFORMER);
    public static final BlockEntityType<TileEntityTesla> TESLA_COIL = Ic2BlockEntities.register("tesla_coil", (BiFunction<BlockPos, BlockState, TileEntityTesla>)TileEntityTesla::new, Ic2Blocks.TESLA_COIL);
    public static final BlockEntityType<TileEntityCanner> CANNER = Ic2BlockEntities.register("canner", (BiFunction<BlockPos, BlockState, TileEntityCanner>)TileEntityCanner::new, Ic2Blocks.CANNER);
    public static final BlockEntityType<TileEntityClassicCanner> CLASSIC_CANNER = Ic2BlockEntities.register("classic_canner", (BiFunction<BlockPos, BlockState, TileEntityClassicCanner>)TileEntityClassicCanner::new, Ic2Blocks.CLASSIC_CANNER);
    public static final BlockEntityType<TileEntityCompressor> COMPRESSOR = Ic2BlockEntities.register("compressor", (BiFunction<BlockPos, BlockState, TileEntityCompressor>)TileEntityCompressor::new, Ic2Blocks.COMPRESSOR);
    public static final BlockEntityType<TileEntityElectricFurnace> ELECTRIC_FURNACE = Ic2BlockEntities.register("electric_furnace", (BiFunction<BlockPos, BlockState, TileEntityElectricFurnace>)TileEntityElectricFurnace::new, Ic2Blocks.ELECTRIC_FURNACE);
    public static final BlockEntityType<TileEntityExtractor> EXTRACTOR = Ic2BlockEntities.register("extractor", (BiFunction<BlockPos, BlockState, TileEntityExtractor>)TileEntityExtractor::new, Ic2Blocks.EXTRACTOR);
    public static final BlockEntityType<TileEntityIronFurnace> IRON_FURNACE = Ic2BlockEntities.register("iron_furnace", (BiFunction<BlockPos, BlockState, TileEntityIronFurnace>)TileEntityIronFurnace::new, Ic2Blocks.IRON_FURNACE);
    public static final BlockEntityType<TileEntityMacerator> MACERATOR = Ic2BlockEntities.register("macerator", (BiFunction<BlockPos, BlockState, TileEntityMacerator>)TileEntityMacerator::new, Ic2Blocks.MACERATOR);
    public static final BlockEntityType<TileEntityRecycler> RECYCLER = Ic2BlockEntities.register("recycler", (BiFunction<BlockPos, BlockState, TileEntityRecycler>)TileEntityRecycler::new, Ic2Blocks.RECYCLER);
    public static final BlockEntityType<TileEntitySolidCanner> SOLID_CANNER = Ic2BlockEntities.register("solid_canner", (BiFunction<BlockPos, BlockState, TileEntitySolidCanner>)TileEntitySolidCanner::new, Ic2Blocks.SOLID_CANNER);
    public static final BlockEntityType<TileEntityBlastFurnace> BLAST_FURNACE = Ic2BlockEntities.register("blast_furnace", (BiFunction<BlockPos, BlockState, TileEntityBlastFurnace>)TileEntityBlastFurnace::new, Ic2Blocks.BLAST_FURNACE);
    public static final BlockEntityType<TileEntityBlockCutter> BLOCK_CUTTER = Ic2BlockEntities.register("block_cutter", (BiFunction<BlockPos, BlockState, TileEntityBlockCutter>)TileEntityBlockCutter::new, Ic2Blocks.BLOCK_CUTTER);
    public static final BlockEntityType<TileEntityCentrifuge> CENTRIFUGE = Ic2BlockEntities.register("centrifuge", (BiFunction<BlockPos, BlockState, TileEntityCentrifuge>)TileEntityCentrifuge::new, Ic2Blocks.CENTRIFUGE);
    public static final BlockEntityType<TileEntityFermenter> FERMENTER = Ic2BlockEntities.register("fermenter", (BiFunction<BlockPos, BlockState, TileEntityFermenter>)TileEntityFermenter::new, Ic2Blocks.FERMENTER);
    public static final BlockEntityType<TileEntityInduction> INDUCTION_FURNACE = Ic2BlockEntities.register("induction_furnace", (BiFunction<BlockPos, BlockState, TileEntityInduction>)TileEntityInduction::new, Ic2Blocks.INDUCTION_FURNACE);
    public static final BlockEntityType<TileEntityMetalFormer> METAL_FORMER = Ic2BlockEntities.register("metal_former", (BiFunction<BlockPos, BlockState, TileEntityMetalFormer>)TileEntityMetalFormer::new, Ic2Blocks.METAL_FORMER);
    public static final BlockEntityType<TileEntityOreWashing> ORE_WASHING_PLANT = Ic2BlockEntities.register("ore_washing_plant", (BiFunction<BlockPos, BlockState, TileEntityOreWashing>)TileEntityOreWashing::new, Ic2Blocks.ORE_WASHING_PLANT);
    public static final BlockEntityType<TileEntityAdvMiner> ADVANCED_MINER = Ic2BlockEntities.register("advanced_miner", (BiFunction<BlockPos, BlockState, TileEntityAdvMiner>)TileEntityAdvMiner::new, Ic2Blocks.ADVANCED_MINER);
    public static final BlockEntityType<TileEntityCropHarvester> CROP_HARVESTER = Ic2BlockEntities.register("crop_harvester", (BiFunction<BlockPos, BlockState, TileEntityCropHarvester>)TileEntityCropHarvester::new, Ic2Blocks.CROP_HARVESTER);
    public static final BlockEntityType<TileEntityCropmatron> CROPMATRON = Ic2BlockEntities.register("cropmatron", (BiFunction<BlockPos, BlockState, TileEntityCropmatron>)TileEntityCropmatron::new, Ic2Blocks.CROPMATRON);
    public static final BlockEntityType<TileEntityClassicCropmatron> CLASSIC_CROPMATRON = Ic2BlockEntities.register("classic_cropmatron", (BiFunction<BlockPos, BlockState, TileEntityClassicCropmatron>)TileEntityClassicCropmatron::new, Ic2Blocks.CLASSIC_CROPMATRON);
    public static final BlockEntityType<TileEntityMiner> MINER = Ic2BlockEntities.register("miner", (BiFunction<BlockPos, BlockState, TileEntityMiner>)TileEntityMiner::new, Ic2Blocks.MINER);
    public static final BlockEntityType<TileEntityMassFabricator> MASS_FABRICATOR = Ic2BlockEntities.register("mass_fabricator", (BiFunction<BlockPos, BlockState, TileEntityMassFabricator>)TileEntityMassFabricator::new, Ic2Blocks.MASS_FABRICATOR);
    public static final BlockEntityType<TileEntityClassicMassFabricator> CLASSIC_MASS_FABRICATOR = Ic2BlockEntities.register("classic_mass_fabricator", (BiFunction<BlockPos, BlockState, TileEntityClassicMassFabricator>)TileEntityClassicMassFabricator::new, Ic2Blocks.CLASSIC_MASS_FABRICATOR);
    public static final BlockEntityType<TileEntityAssemblyBench> UU_ASSEMBLY_BENCH = Ic2BlockEntities.register("uu_assembly_bench", (BiFunction<BlockPos, BlockState, TileEntityAssemblyBench>)TileEntityAssemblyBench::new, Ic2Blocks.UU_ASSEMBLY_BENCH);
    public static final BlockEntityType<TileEntityMatter> MATTER_GENERATOR = Ic2BlockEntities.register("matter_generator", (BiFunction<BlockPos, BlockState, TileEntityMatter>)TileEntityMatter::new, Ic2Blocks.MATTER_GENERATOR);
    public static final BlockEntityType<TileEntityPatternStorage> PATTERN_STORAGE = Ic2BlockEntities.register("pattern_storage", (BiFunction<BlockPos, BlockState, TileEntityPatternStorage>)TileEntityPatternStorage::new, Ic2Blocks.PATTERN_STORAGE);
    public static final BlockEntityType<TileEntityReplicator> REPLICATOR = Ic2BlockEntities.register("replicator", (BiFunction<BlockPos, BlockState, TileEntityReplicator>)TileEntityReplicator::new, Ic2Blocks.REPLICATOR);
    public static final BlockEntityType<TileEntityScanner> UU_SCANNER = Ic2BlockEntities.register("uu_scanner", (BiFunction<BlockPos, BlockState, TileEntityScanner>)TileEntityScanner::new, Ic2Blocks.UU_SCANNER);
    public static final BlockEntityType<TileEntityEnergyOMat> ENERGY_O_MAT = Ic2BlockEntities.register("energy_o_mat", (BiFunction<BlockPos, BlockState, TileEntityEnergyOMat>)TileEntityEnergyOMat::new, Ic2Blocks.ENERGY_O_MAT);
    public static final BlockEntityType<TileEntityPersonalChest> PERSONAL_CHEST = Ic2BlockEntities.register("personal_chest", (BiFunction<BlockPos, BlockState, TileEntityPersonalChest>)TileEntityPersonalChest::new, Ic2Blocks.PERSONAL_CHEST);
    public static final BlockEntityType<TileEntityTradeOMat> TRADE_O_MAT = Ic2BlockEntities.register("trade_o_mat", (BiFunction<BlockPos, BlockState, TileEntityTradeOMat>)TileEntityTradeOMat::new, Ic2Blocks.TRADE_O_MAT);
    public static final BlockEntityType<TileEntityChargepadBatBox> BATBOX_CHARGEPAD = Ic2BlockEntities.register("batbox_chargepad", (BiFunction<BlockPos, BlockState, TileEntityChargepadBatBox>)TileEntityChargepadBatBox::new, Ic2Blocks.BATBOX_CHARGEPAD);
    public static final BlockEntityType<TileEntityChargepadCESU> CESU_CHARGEPAD = Ic2BlockEntities.register("cesu_chargepad", (BiFunction<BlockPos, BlockState, TileEntityChargepadCESU>)TileEntityChargepadCESU::new, Ic2Blocks.CESU_CHARGEPAD);
    public static final BlockEntityType<TileEntityChargepadMFE> MFE_CHARGEPAD = Ic2BlockEntities.register("mfe_chargepad", (BiFunction<BlockPos, BlockState, TileEntityChargepadMFE>)TileEntityChargepadMFE::new, Ic2Blocks.MFE_CHARGEPAD);
    public static final BlockEntityType<TileEntityChargepadMFSU> MFSU_CHARGEPAD = Ic2BlockEntities.register("mfsu_chargepad", (BiFunction<BlockPos, BlockState, TileEntityChargepadMFSU>)TileEntityChargepadMFSU::new, Ic2Blocks.MFSU_CHARGEPAD);
    public static final BlockEntityType<TileEntityElectricBatBox> BATBOX = Ic2BlockEntities.register("batbox", (BiFunction<BlockPos, BlockState, TileEntityElectricBatBox>)TileEntityElectricBatBox::new, Ic2Blocks.BATBOX);
    public static final BlockEntityType<TileEntityElectricCESU> CESU = Ic2BlockEntities.register("cesu", (BiFunction<BlockPos, BlockState, TileEntityElectricCESU>)TileEntityElectricCESU::new, Ic2Blocks.CESU);
    public static final BlockEntityType<TileEntityElectricMFE> MFE = Ic2BlockEntities.register("mfe", (BiFunction<BlockPos, BlockState, TileEntityElectricMFE>)TileEntityElectricMFE::new, Ic2Blocks.MFE);
    public static final BlockEntityType<TileEntityElectricMFE.TileEntityElectricClassicMFE> CLASSIC_MFE = Ic2BlockEntities.register("classic_mfe", (BiFunction<BlockPos, BlockState, TileEntityElectricMFE.TileEntityElectricClassicMFE>)TileEntityElectricMFE.TileEntityElectricClassicMFE::new, Ic2Blocks.CLASSIC_MFE);
    public static final BlockEntityType<TileEntityElectricMFSU> MFSU = Ic2BlockEntities.register("mfsu", (BiFunction<BlockPos, BlockState, TileEntityElectricMFSU>)TileEntityElectricMFSU::new, Ic2Blocks.MFSU);
    public static final BlockEntityType<TileEntityElectricMFSU.TileEntityElectricClassicMFSU> CLASSIC_MFSU = Ic2BlockEntities.register("classic_mfsu", (BiFunction<BlockPos, BlockState, TileEntityElectricMFSU.TileEntityElectricClassicMFSU>)TileEntityElectricMFSU.TileEntityElectricClassicMFSU::new, Ic2Blocks.CLASSIC_MFSU);
    public static final BlockEntityType<TileEntityElectrolyzer> ELECTROLYZER = Ic2BlockEntities.register("electrolyzer", (BiFunction<BlockPos, BlockState, TileEntityElectrolyzer>)TileEntityElectrolyzer::new, Ic2Blocks.ELECTROLYZER);
    public static final BlockEntityType<TileEntityClassicElectrolyzer> CLASSIC_ELECTROLYZER = Ic2BlockEntities.register("classic_electrolyzer", (BiFunction<BlockPos, BlockState, TileEntityClassicElectrolyzer>)TileEntityClassicElectrolyzer::new, Ic2Blocks.CLASSIC_ELECTROLYZER);
    public static final BlockEntityType<TileEntityTransformerLV> LV_TRANSFORMER = Ic2BlockEntities.register("lv_transformer", (BiFunction<BlockPos, BlockState, TileEntityTransformerLV>)TileEntityTransformerLV::new, Ic2Blocks.LV_TRANSFORMER);
    public static final BlockEntityType<TileEntityTransformerMV> MV_TRANSFORMER = Ic2BlockEntities.register("mv_transformer", (BiFunction<BlockPos, BlockState, TileEntityTransformerMV>)TileEntityTransformerMV::new, Ic2Blocks.MV_TRANSFORMER);
    public static final BlockEntityType<TileEntityTransformerHV> HV_TRANSFORMER = Ic2BlockEntities.register("hv_transformer", (BiFunction<BlockPos, BlockState, TileEntityTransformerHV>)TileEntityTransformerHV::new, Ic2Blocks.HV_TRANSFORMER);
    public static final BlockEntityType<TileEntityTransformerEV> EV_TRANSFORMER = Ic2BlockEntities.register("ev_transformer", (BiFunction<BlockPos, BlockState, TileEntityTransformerEV>)TileEntityTransformerEV::new, Ic2Blocks.EV_TRANSFORMER);
    public static final BlockEntityType<TileEntityTank> TANK = Ic2BlockEntities.register("tank", (BiFunction<BlockPos, BlockState, TileEntityTank>)TileEntityTank::new, Ic2Blocks.TANK);
    public static final BlockEntityType<TileEntityChunkloader> CHUNK_LOADER = Ic2BlockEntities.register("chunk_loader", (BiFunction<BlockPos, BlockState, TileEntityChunkloader>)TileEntityChunkloader::new, Ic2Blocks.CHUNK_LOADER);
    public static final BlockEntityType<TileEntityCreativeGenerator> CREATIVE_GENERATOR = Ic2BlockEntities.register("creative_generator", (BiFunction<BlockPos, BlockState, TileEntityCreativeGenerator>)TileEntityCreativeGenerator::new, Ic2Blocks.CREATIVE_GENERATOR);
    public static final BlockEntityType<TileEntitySteamRepressurizer> STEAM_REPRESSURIZER = Ic2BlockEntities.register("steam_repressurizer", (BiFunction<BlockPos, BlockState, TileEntitySteamRepressurizer>)TileEntitySteamRepressurizer::new, Ic2Blocks.STEAM_REPRESSURIZER);
    public static final BlockEntityType<TileEntityWeightedFluidDistributor> WEIGHTED_FLUID_DISTRIBUTOR = Ic2BlockEntities.register("weighted_fluid_distributor", (BiFunction<BlockPos, BlockState, TileEntityWeightedFluidDistributor>)TileEntityWeightedFluidDistributor::new, Ic2Blocks.WEIGHTED_FLUID_DISTRIBUTOR);
    public static final BlockEntityType<TileEntityWeightedItemDistributor> WEIGHTED_ITEM_DISTRIBUTOR = Ic2BlockEntities.register("weighted_item_distributor", (BiFunction<BlockPos, BlockState, TileEntityWeightedItemDistributor>)TileEntityWeightedItemDistributor::new, Ic2Blocks.WEIGHTED_ITEM_DISTRIBUTOR);
    public static final BlockEntityType<TileEntityRCI_RSH> RCI_RSH = Ic2BlockEntities.register("rci_rsh", (BiFunction<BlockPos, BlockState, TileEntityRCI_RSH>)TileEntityRCI_RSH::new, Ic2Blocks.RCI_RSH);
    public static final BlockEntityType<TileEntityRCI_LZH> RCI_LZH = Ic2BlockEntities.register("rci_lzh", (BiFunction<BlockPos, BlockState, TileEntityRCI_LZH>)TileEntityRCI_LZH::new, Ic2Blocks.RCI_LZH);
    public static final BlockEntityType<TileEntityCrop> CROP_STICK = Ic2BlockEntities.register("crop_stick", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.CROP_STICK);
    public static final BlockEntityType<TileEntityCrop> WEED_CROP = Ic2BlockEntities.register("weed_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.WEED_CROP);
    public static final BlockEntityType<TileEntityCrop> WHEAT_CROP = Ic2BlockEntities.register("wheat_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.WHEAT_CROP);
    public static final BlockEntityType<TileEntityCrop> CARROTS_CROP = Ic2BlockEntities.register("carrots_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.CARROTS_CROP);
    public static final BlockEntityType<TileEntityCrop> POTATO_CROP = Ic2BlockEntities.register("potato_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.POTATO_CROP);
    public static final BlockEntityType<TileEntityCrop> BEETROOTS_CROP = Ic2BlockEntities.register("beetroots_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.BEETROOTS_CROP);
    public static final BlockEntityType<TileEntityCrop> PUMPKIN_CROP = Ic2BlockEntities.register("pumpkin_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.PUMPKIN_CROP);
    public static final BlockEntityType<TileEntityCrop> MELON_CROP = Ic2BlockEntities.register("melon_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.MELON_CROP);
    public static final BlockEntityType<TileEntityCrop> DANDELION_CROP = Ic2BlockEntities.register("dandelion_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.DANDELION_CROP);
    public static final BlockEntityType<TileEntityCrop> POPPY_CROP = Ic2BlockEntities.register("poppy_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.POPPY_CROP);
    public static final BlockEntityType<TileEntityCrop> BLACKTHORN_CROP = Ic2BlockEntities.register("blackthorn_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.BLACKTHORN_CROP);
    public static final BlockEntityType<TileEntityCrop> TULIP_CROP = Ic2BlockEntities.register("tulip_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.TULIP_CROP);
    public static final BlockEntityType<TileEntityCrop> CYAZINT_CROP = Ic2BlockEntities.register("cyazint_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.CYAZINT_CROP);
    public static final BlockEntityType<TileEntityCrop> VENOMILIA_CROP = Ic2BlockEntities.register("venomilia_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.VENOMILIA_CROP);
    public static final BlockEntityType<TileEntityCrop> REED_CROP = Ic2BlockEntities.register("reed_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.REED_CROP);
    public static final BlockEntityType<TileEntityCrop> STICKY_REED_CROP = Ic2BlockEntities.register("sticky_reed_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.STICKY_REED_CROP);
    public static final BlockEntityType<TileEntityCrop> COCOA_CROP = Ic2BlockEntities.register("cocoa_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.COCOA_CROP);
    public static final BlockEntityType<TileEntityCrop> FLAX_CROP = Ic2BlockEntities.register("flax_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.FLAX_CROP);
    public static final BlockEntityType<TileEntityCrop> RED_MUSHROOM_CROP = Ic2BlockEntities.register("red_mushroom_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.RED_MUSHROOM_CROP);
    public static final BlockEntityType<TileEntityCrop> BROWN_MUSHROOM_CROP = Ic2BlockEntities.register("brown_mushroom_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.BROWN_MUSHROOM_CROP);
    public static final BlockEntityType<TileEntityCrop> NETHER_WART_CROP = Ic2BlockEntities.register("nether_wart_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.NETHER_WART_CROP);
    public static final BlockEntityType<TileEntityCrop> TERRA_WART_CROP = Ic2BlockEntities.register("terra_wart_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.TERRA_WART_CROP);
    public static final BlockEntityType<TileEntityCrop> OAK_SAPLING_CROP = Ic2BlockEntities.register("oak_sapling_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.OAK_SAPLING_CROP);
    public static final BlockEntityType<TileEntityCrop> SPRUCE_SAPLING_CROP = Ic2BlockEntities.register("spruce_sapling_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.SPRUCE_SAPLING_CROP);
    public static final BlockEntityType<TileEntityCrop> BIRCH_SAPLING_CROP = Ic2BlockEntities.register("birch_sapling_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.BIRCH_SAPLING_CROP);
    public static final BlockEntityType<TileEntityCrop> JUNGLE_SAPLING_CROP = Ic2BlockEntities.register("jungle_sapling_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.JUNGLE_SAPLING_CROP);
    public static final BlockEntityType<TileEntityCrop> ACACIA_SAPLING_CROP = Ic2BlockEntities.register("acacia_sapling_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.ACACIA_SAPLING_CROP);
    public static final BlockEntityType<TileEntityCrop> DARK_OAK_SAPLING_CROP = Ic2BlockEntities.register("dark_oak_sapling_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.DARK_OAK_SAPLING_CROP);
    public static final BlockEntityType<TileEntityCrop> FERRU_CROP = Ic2BlockEntities.register("ferru_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.FERRU_CROP);
    public static final BlockEntityType<TileEntityCrop> CYPRIUM_CROP = Ic2BlockEntities.register("cyprium_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.CYPRIUM_CROP);
    public static final BlockEntityType<TileEntityCrop> STAGNIUM_CROP = Ic2BlockEntities.register("stagnium_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.STAGNIUM_CROP);
    public static final BlockEntityType<TileEntityCrop> PLUMBISCUS_CROP = Ic2BlockEntities.register("plumbiscus_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.PLUMBISCUS_CROP);
    public static final BlockEntityType<TileEntityCrop> AURELIA_CROP = Ic2BlockEntities.register("aurelia_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.AURELIA_CROP);
    public static final BlockEntityType<TileEntityCrop> SHINING_CROP = Ic2BlockEntities.register("shining_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.SHINING_CROP);
    public static final BlockEntityType<TileEntityCrop> RED_WHEAT_CROP = Ic2BlockEntities.register("red_wheat_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.RED_WHEAT_CROP);
    public static final BlockEntityType<TileEntityCrop> COFFEE_CROP = Ic2BlockEntities.register("coffee_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.COFFEE_CROP);
    public static final BlockEntityType<TileEntityCrop> HOPS_CROP = Ic2BlockEntities.register("hops_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.HOPS_CROP);
    public static final BlockEntityType<TileEntityCrop> EATING_PLANT_CROP = Ic2BlockEntities.register("eating_plant_crop", (BiFunction<BlockPos, BlockState, TileEntityCrop>)TileEntityCrop::new, Ic2Blocks.EATING_PLANT_CROP);
    public static final BlockEntityType<TileEntityIndustrialWorkbench> INDUSTRIAL_WORKBENCH = Ic2BlockEntities.register("industrial_workbench", (BiFunction<BlockPos, BlockState, TileEntityIndustrialWorkbench>)TileEntityIndustrialWorkbench::new, Ic2Blocks.INDUSTRIAL_WORKBENCH);
    public static final BlockEntityType<TileEntityBatchCrafter> BATCH_CRAFTER = Ic2BlockEntities.register("batch_crafter", (BiFunction<BlockPos, BlockState, TileEntityBatchCrafter>)TileEntityBatchCrafter::new, Ic2Blocks.BATCH_CRAFTER);
    public static final BlockEntityType<TileEntityWoodenStorageBox> WOODEN_STORAGE_BOX = Ic2BlockEntities.register("wooden_storage_box", (BiFunction<BlockPos, BlockState, TileEntityWoodenStorageBox>)TileEntityWoodenStorageBox::new, Ic2Blocks.WOODEN_STORAGE_BOX);
    public static final BlockEntityType<TileEntityIronStorageBox> IRON_STORAGE_BOX = Ic2BlockEntities.register("iron_storage_box", (BiFunction<BlockPos, BlockState, TileEntityIronStorageBox>)TileEntityIronStorageBox::new, Ic2Blocks.IRON_STORAGE_BOX);
    public static final BlockEntityType<TileEntityBronzeStorageBox> BRONZE_STORAGE_BOX = Ic2BlockEntities.register("bronze_storage_box", (BiFunction<BlockPos, BlockState, TileEntityBronzeStorageBox>)TileEntityBronzeStorageBox::new, Ic2Blocks.BRONZE_STORAGE_BOX);
    public static final BlockEntityType<TileEntitySteelStorageBox> STEEL_STORAGE_BOX = Ic2BlockEntities.register("steel_storage_box", (BiFunction<BlockPos, BlockState, TileEntitySteelStorageBox>)TileEntitySteelStorageBox::new, Ic2Blocks.STEEL_STORAGE_BOX);
    public static final BlockEntityType<TileEntityIridiumStorageBox> IRIDIUM_STORAGE_BOX = Ic2BlockEntities.register("iridium_storage_box", (BiFunction<BlockPos, BlockState, TileEntityIridiumStorageBox>)TileEntityIridiumStorageBox::new, Ic2Blocks.IRIDIUM_STORAGE_BOX);
    public static final BlockEntityType<TileEntityBronzeTank> BRONZE_TANK = Ic2BlockEntities.register("bronze_tank", (BiFunction<BlockPos, BlockState, TileEntityBronzeTank>)TileEntityBronzeTank::new, Ic2Blocks.BRONZE_TANK);
    public static final BlockEntityType<TileEntityIronTank> IRON_TANK = Ic2BlockEntities.register("iron_tank", (BiFunction<BlockPos, BlockState, TileEntityIronTank>)TileEntityIronTank::new, Ic2Blocks.IRON_TANK);
    public static final BlockEntityType<TileEntitySteelTank> STEEL_TANK = Ic2BlockEntities.register("steel_tank", (BiFunction<BlockPos, BlockState, TileEntitySteelTank>)TileEntitySteelTank::new, Ic2Blocks.STEEL_TANK);
    public static final BlockEntityType<TileEntityIridiumTank> IRIDIUM_TANK = Ic2BlockEntities.register("iridium_tank", (BiFunction<BlockPos, BlockState, TileEntityIridiumTank>)TileEntityIridiumTank::new, Ic2Blocks.IRIDIUM_TANK);
    private static Map<String, BlockEntityType<?>> blockEntityTypeMap;

    public static void init() {
    }

    private static <T extends BlockEntity> BlockEntityType<T> register(String string, BiFunction<BlockPos, BlockState, T> biFunction, Block ... blockArray) {
        if (blockEntityTypeMap == null) {
            blockEntityTypeMap = new HashMap();
        }
        ResourceLocation resourceLocation = IC2.getIdentifier(string);
        BlockEntityType<T> blockEntityType = IC2.envProxy.registerBlockEntity(resourceLocation, biFunction, blockArray);
        blockEntityTypeMap.put(resourceLocation.toString(), blockEntityType);
        return blockEntityType;
    }

    public static BlockEntityType<?> get(ResourceLocation resourceLocation) {
        return blockEntityTypeMap.get(resourceLocation.toString());
    }
}

